# Проект по биоинформатике. Anopheles stephensi

# Импорты и загрузки

In [1]:
!pip install biopython
!pip install fuc
!apt-get install bedtools

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.Data import CodonTable
from Bio import Entrez
from Bio.SeqFeature import SeqFeature, FeatureLocation
import pandas as pd

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 80.4 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.87
Collecting fuc
  Downloading fuc-0.38.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: biopython in /usr/local/lib/python3.12/dist-packages (from fuc) (1.87)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from fuc) (6.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from fuc) (3.10.0)
Requirement already satisfied: matplotlib-venn in /usr/local/lib/python3.12/dist-packages (from fuc) (1.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fuc) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from fuc) (2.2.2)
Collecting pyranges (from fuc)
  Downloading pyranges-0.1.4-py3-none-any.whl.metadata (3.7 kB)
Collecting pysam (from fuc)
  Downloading pysam-0.24.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from fuc) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from fuc) (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from fuc) (0.14.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->fuc) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->fuc) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->fuc) (2026.2)
Collecting ncls>=0.0.63 (from pyranges->fuc)
  Downloading ncls-0.0.70-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pyranges->fuc) (0.9.0)
Collecting sorted_nearest>=0.0.33 (from pyranges->fuc)
  Downloading sorted_nearest-0.0.41.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 68.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from pyranges->fuc) (8.4.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->fuc) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->fuc) (1.17.0)
Downloading fuc-0.38.0-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 13.9 MB/s eta 0:00:00
Downloading pyranges-0.1.4-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 74.0 MB/s eta 0:00:00
Downloading pysam-0.24.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 68.8 MB/s eta 0:00:00
Downloading ncls-0.0.70-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 88.2 MB/s eta 0:00:00
Building wheels for collected packages: sorted_nearest
  Building wheel for sorted_nearest (pyproject.toml) ... done
  Created wheel for sorted_nearest: filename=sorted_nearest-0.0.41-cp312-cp312-linux_x86_64.whl size=6690263 sha256=4a55fda4c6847b7cd56947976e7987cae6587324e76d2ade01c8f659b37f2e4e
  Stored in directory: /root/.cache/pip/wheels/7c/cb/a4/a6f831a60e479b9001be190e91000cc472addeab871957e5a9
Successfully built sorted_nearest
Installing collected packages: sorted_nearest, pysam, ncls, pyranges, fuc
Successfully installed fuc-0.38.0 ncls-0.0.70 pyranges-0.1.4 pysam-0.24.0 sorted_nearest-0.0.41
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  bedtools
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 563 kB of archives.
After this operation, 1,548 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 bedtools amd64 2.30.0+dfsg-2ubuntu0.1 [563 kB]
Fetched 563 kB in 0s (9,653 kB/s)
Selecting previously unselected package bedtools.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../bedtools_2.30.0+dfsg-2ubuntu0.1_amd64.deb ...
Unpacking bedtools (2.30.0+dfsg-2ubuntu0.1) ...
Setting up bedtools (2.30.0+dfsg-2ubuntu0.1) ...

In [2]:
!gdown "1lqiyL7d9Zu4ztkCTwpJKVfSwqoJmAp-b" # genomic.fna


scaffolds = {}
for scaffold in SeqIO.parse('GCF_013141755.1_UCI_ANSTEP_V1.0_genomic.fna', format='fasta'):
    scaffolds[scaffold.id] = scaffold
len(scaffolds)

Downloading...
From (original): https://drive.google.com/uc?id=1lqiyL7d9Zu4ztkCTwpJKVfSwqoJmAp-b
From (redirected): https://drive.google.com/uc?id=1lqiyL7d9Zu4ztkCTwpJKVfSwqoJmAp-b&confirm=t&uuid=379554fa-8464-4172-9c33-b1d197cb81b0
To: /content/GCF_013141755.1_UCI_ANSTEP_V1.0_genomic.fna
100% 247M/247M [00:05<00:00, 47.0MB/s]

494

Протеомы

In [3]:
!gdown "19TECLovpngLrwcamfVbsX5kncOfs4htI"    # genomic.gff

annotation_df = pd.read_csv(
    'genomic.gff',
    sep='\t',
    comment='#',
    header=None,
    names=["scaffold", "source", "type", "start", "end", "score", "strand", "phase", "attributes"]
)

cds_df = annotation_df[annotation_df['type'] == 'CDS'].reset_index()
print(f"Найдено {len(cds_df)} CDS")

Downloading...
From (original): https://drive.google.com/uc?id=19TECLovpngLrwcamfVbsX5kncOfs4htI
From (redirected): https://drive.google.com/uc?id=19TECLovpngLrwcamfVbsX5kncOfs4htI&confirm=t&uuid=d884597f-f929-455f-8918-0691150bcc60
To: /content/genomic.gff
100% 132M/132M [00:02<00:00, 57.7MB/s]
Найдено 191820 CDS

In [4]:
with open('proteins.fasta', 'w') as prot_file:
    cur_transcript=None
    cur_cds = Seq("")
    for index, row in cds_df.iterrows():
        attrs = row['attributes'].split(';')
        parent = attrs[1]
        gene = attrs[5]
        phase = 0
        if parent != cur_transcript:
            if index != 0:
                if strand == '-':
                    cur_cds = cur_cds.reverse_complement()
                protein_seq = cur_cds.translate(to_stop=True)
                prot_file.write(f'>{gene} scaffold={scaffold} strand={strand} {cur_transcript} \n')
                prot_file.write(f'{str(protein_seq)}\n')

            cur_transcript = parent
            cur_cds = Seq("")
            strand = row['strand']
            phase = int(row['phase'])
            scaffold = row['scaffold']

        beg = row['start'] - 1 + phase
        end = row['end']
        seq = scaffolds[scaffold].seq[beg:end]
        cur_cds = cur_cds + seq

    if strand == '-':
        cur_cds = cur_cds.reverse_complement()
    protein_seq = cur_cds.translate(to_stop=True)
    prot_file.write(f'> {scaffold} {strand} {cur_transcript}\n')
    prot_file.write(f'{str(protein_seq)}\n')

/usr/local/lib/python3.12/dist-packages/Bio/Seq.py:2874: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

# 1. Проверка генов на эпигенетику

Подготовка

In [5]:
%%bash
wget http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
tar xf hmmer-3.3.2.tar.gz
cd hmmer-3.3.2
./configure
make
make install

configure: Configuring HMMER3 for your system.
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for strip... strip
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether gcc can compile our Altivec/VMX code... no
checking whether gcc can compile our SSE code... yes
configure: Activating Intel/AMD SSE vector DP implementation
checking whether _MM_SET_FLUSH_ZERO_MODE is supported... yes
checking compiler support --start-group... yes
checking for gzip... /usr/bin/gzip
checking for python3... yes
checking for library containing clock_gettime... none required
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for sys/sysctl.h... no
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for off_t... yes
checking whether byte ordering is bigendian... no
checking for __attribute__((noreturn))... yes
checking for __attribute__((format))... yes
checking for mkstemp... yes
checking for popen... yes
checking for putenv... yes
checking for strcasecmp... yes
checking for strsep... yes
checking for times... yes
checking for getpid... yes
checking for sysctl... no
checking for sysconf... yes
checking for getcwd... yes
checking for chmod... yes
checking for stat... yes
checking for fstat... yes
checking for erfc... no
checking for library containing ntohs... none required
checking for library containing ntohl... none required
checking for library containing htons... none required
checking for library containing htonl... none required
checking for library containing socket... none required
checking for library containing inet_pton... none required
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating testsuite/Makefile
config.status: creating profmark/Makefile
config.status: creating src/impl_sse/Makefile
config.status: creating documentation/Makefile
config.status: creating documentation/man/Makefile
config.status: creating documentation/userguide/Makefile
config.status: creating documentation/userguide/inclusions/Makefile
config.status: creating libdivsufsort/Makefile
config.status: creating easel/Makefile
config.status: creating easel/miniapps/Makefile
config.status: creating easel/testsuite/Makefile
config.status: creating easel/documentation/Makefile
config.status: creating documentation/userguide/titlepage.tex
config.status: creating documentation/userguide/titlepage_daemon.tex
config.status: creating documentation/userguide/copyright.tex
config.status: creating documentation/man/alimask.man
config.status: creating documentation/man/hmmalign.man
config.status: creating documentation/man/hmmbuild.man
config.status: creating documentation/man/hmmc2.man
config.status: creating documentation/man/hmmconvert.man
config.status: creating documentation/man/hmmemit.man
config.status: creating documentation/man/hmmer.man
config.status: creating documentation/man/hmmfetch.man
config.status: creating documentation/man/hmmlogo.man
config.status: creating documentation/man/hmmpgmd.man
config.status: creating documentation/man/hmmpgmd_shard.man
config.status: creating documentation/man/hmmpress.man
config.status: creating documentation/man/hmmscan.man
config.status: creating documentation/man/hmmsearch.man
config.status: creating documentation/man/hmmsim.man
config.status: creating documentation/man/hmmstat.man
config.status: creating documentation/man/jackhmmer.man
config.status: creating documentation/man/makehmmerdb.man
config.status: creating documentation/man/nhmmer.man
config.status: creating documentation/man/nhmmscan.man
config.status: creating documentation/man/phmmer.man
config.status: creating easel/miniapps/esl-afetch.man
config.status: creating easel/miniapps/esl-alimanip.man
config.status: creating easel/miniapps/esl-alimap.man
config.status: creating easel/miniapps/esl-alimask.man
config.status: creating easel/miniapps/esl-alimerge.man
config.status: creating easel/miniapps/esl-alipid.man
config.status: creating easel/miniapps/esl-alirev.man
config.status: creating easel/miniapps/esl-alistat.man
config.status: creating easel/miniapps/esl-compalign.man
config.status: creating easel/miniapps/esl-compstruct.man
config.status: creating easel/miniapps/esl-construct.man
config.status: creating easel/miniapps/esl-histplot.man
config.status: creating easel/miniapps/esl-mask.man
config.status: creating easel/miniapps/esl-mixdchlet.man
config.status: creating easel/miniapps/esl-reformat.man
config.status: creating easel/miniapps/esl-selectn.man
config.status: creating easel/miniapps/esl-seqrange.man
config.status: creating easel/miniapps/esl-seqstat.man
config.status: creating easel/miniapps/esl-sfetch.man
config.status: creating easel/miniapps/esl-shuffle.man
config.status: creating easel/miniapps/esl-ssdraw.man
config.status: creating easel/miniapps/esl-translate.man
config.status: creating easel/miniapps/esl-weight.man
config.status: creating easel/decoy_config.h
config.status: creating src/p7_config.h
config.status: creating easel/esl_config.h
config.status: creating libdivsufsort/divsufsort.h
config.status: linking src/impl_sse to src/impl


HMMER configuration:
   compiler:             gcc -O3   -pthread
   host:                 x86_64-pc-linux-gnu
   linker:
   libraries:
   DP implementation:    sse

Now do 'make'  to build HMMER, and optionally:
       'make check'  to run self tests,
       'make install'  to install programs and man pages,
       '(cd easel; make install)'  to install Easel tools.

     SUBDIR easel
     CC easel.o
     CC esl_alloc.o
     CC esl_alphabet.o
     CC esl_arr2.o
     CC esl_arr3.o
     CC esl_bitfield.o
     CC esl_buffer.o
     CC esl_cluster.o
     CC esl_composition.o
     CC esl_cpu.o
     CC esl_dirichlet.o
     CC esl_distance.o
     CC esl_dmatrix.o
     CC esl_dsqdata.o
     CC esl_exponential.o
     CC esl_fileparser.o
     CC esl_gamma.o
     CC esl_gencode.o
     CC esl_getopts.o
     CC esl_gev.o
     CC esl_graph.o
     CC esl_gumbel.o
     CC esl_heap.o
     CC esl_histogram.o
     CC esl_hmm.o
     CC esl_huffman.o
     CC esl_hyperexp.o
     CC esl_json.o
     CC esl_keyhash.o
     CC esl_matrixops.o
     CC esl_mem.o
     CC esl_minimizer.o
     CC esl_mixdchlet.o
     CC esl_mixgev.o
     CC esl_mpi.o
     CC esl_msa.o
     CC esl_msacluster.o
     CC esl_msafile.o
     CC esl_msafile2.o
     CC esl_msafile_a2m.o
     CC esl_msafile_afa.o
     CC esl_msafile_clustal.o
     CC esl_msafile_phylip.o
     CC esl_msafile_psiblast.o
     CC esl_msafile_selex.o
     CC esl_msafile_stockholm.o
     CC esl_msashuffle.o
     CC esl_msaweight.o
     CC esl_normal.o
     CC esl_paml.o
     CC esl_quicksort.o
     CC esl_random.o
     CC esl_rand64.o
     CC esl_randomseq.o
     CC esl_ratematrix.o
     CC esl_recorder.o
     CC esl_red_black.o
     CC esl_regexp.o
     CC esl_rootfinder.o
     CC esl_scorematrix.o
     CC esl_sq.o
     CC esl_sqio.o
     CC esl_sqio_ascii.o
     CC esl_sqio_ncbi.o
     CC esl_ssi.o
     CC esl_stack.o
     CC esl_stats.o
     CC esl_stopwatch.o
     CC esl_stretchexp.o
     CC esl_subcmd.o
     CC esl_threads.o
     CC esl_tree.o
     CC esl_varint.o
     CC esl_vectorops.o
     CC esl_weibull.o
     CC esl_workqueue.o
     CC esl_wuss.o
     CC esl_sse.o
     CC esl_avx.o
     CC esl_avx512.o
     CC esl_neon.o
     CC esl_vmx.o
     AR libeasel.a
     SUBDIR miniapps
     GEN esl-afetch
     GEN esl-alimanip
     GEN esl-alimap
     GEN esl-alimask
     GEN esl-alimerge
     GEN esl-alipid
     GEN esl-alirev
     GEN esl-alistat
     GEN esl-compalign
     GEN esl-compstruct
     GEN esl-construct
     GEN esl-histplot
     GEN esl-mask
     GEN esl-mixdchlet
     GEN esl-reformat
     GEN esl-selectn
     GEN esl-seqrange
     GEN esl-seqstat
     GEN esl-sfetch
     GEN esl-shuffle
     GEN esl-ssdraw
     GEN esl-translate
     GEN esl-weight
     CC cmd_alistat.o
     CC cmd_downsample.o
     CC cmd_filter.o
     CC cmd_index.o
     GEN easel
     SUBDIR libdivsufsort
     CC divsufsort.o
     AR libdivsufsort.a
     SUBDIR src
     CC alimask.o
     CC build.o
     CC cachedb.o
     CC cachedb_shard.o
     CC emit.o
     CC errors.o
     CC evalues.o
     CC eweight.o
     CC generic_decoding.o
     CC generic_fwdback.o
     CC generic_fwdback_chk.o
     CC generic_fwdback_banded.o
     CC generic_null2.o
     CC generic_msv.o
     CC generic_optacc.o
     CC generic_stotrace.o
     CC generic_viterbi.o
     CC generic_vtrace.o
     CC h2_io.o
     CC heatmap.o
     CC hmmlogo.o
     CC hmmdmstr.o
     CC hmmdmstr_shard.o
     CC hmmd_search_status.o
     CC hmmdwrkr.o
     CC hmmdwrkr_shard.o
     CC hmmdutils.o
     CC hmmer.o
     CC logsum.o
     CC modelconfig.o
     CC modelstats.o
     CC mpisupport.o
     CC seqmodel.o
     CC tracealign.o
     CC p7_alidisplay.o
     CC p7_bg.o
     CC p7_builder.o
     CC p7_domain.o
     CC p7_domaindef.o
     CC p7_gbands.o
     CC p7_gmx.o
     CC p7_gmxb.o
     CC p7_gmxchk.o
     CC p7_hit.o
     CC p7_hmm.o
     CC p7_hmmcache.o
     CC p7_hmmd_search_stats.o
     CC p7_hmmfile.o
     CC p7_hmmwindow.o
     CC p7_pipeline.o
     CC p7_prior.o
     CC p7_profile.o
     CC p7_spensemble.o
     CC p7_tophits.o
     CC p7_trace.o
     CC p7_scoredata.o
     CC hmmpgmd2msa.o
     CC fm_alphabet.o
     CC fm_general.o
     CC fm_sse.o
     CC fm_ssv.o
     AR libhmmer-src.stamp
     SUBDIR impl_sse
     CC decoding.o
     CC fwdback.o
     CC io.o
     CC ssvfilter.o
     CC msvfilter.o
     CC null2.o
     CC optacc.o
     CC stotrace.o
     CC vitfilter.o
     CC p7_omx.o
     CC p7_oprofile.o
     CC mpi.o
     AR libhmmer-impl.stamp
     GEN alimask
     CC hmmalign.o
     GEN hmmalign
     CC hmmbuild.o
     GEN hmmbuild
     CC hmmconvert.o
     GEN hmmconvert
     CC hmmemit.o
     GEN hmmemit
     CC hmmfetch.o
     GEN hmmfetch
     GEN hmmlogo
     CC hmmpgmd.o
     GEN hmmpgmd
     CC hmmpgmd_shard.o
     GEN hmmpgmd_shard
     CC hmmpress.o
     GEN hmmpress
     CC hmmscan.o
     GEN hmmscan
     CC hmmsearch.o
     GEN hmmsearch
     CC hmmsim.o
     GEN hmmsim
     CC hmmstat.o
     GEN hmmstat
     CC jackhmmer.o
     GEN jackhmmer
     CC phmmer.o
     GEN phmmer
     CC nhmmer.o
     GEN nhmmer
     CC nhmmscan.o
     GEN nhmmscan
     CC makehmmerdb.o
     GEN makehmmerdb
     CC hmmc2.o
     GEN hmmc2
     CC hmmerfm-exactmatch.o
     GEN hmmerfm-exactmatch
     SUBDIR profmark
     CC create-profmark.o
     GEN create-profmark
     CC rocplot.o
     GEN rocplot
     SUBDIR easel
     SUBDIR miniapps
     SUBDIR libdivsufsort
     SUBDIR src
     SUBDIR impl_sse
     SUBDIR profmark
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/share/man/man1
make -C src install
make[1]: Entering directory '/content/hmmer-3.3.2/src'
for file in alimask hmmalign hmmbuild hmmconvert hmmemit hmmfetch hmmlogo hmmpgmd hmmpgmd_shard hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer phmmer nhmmer nhmmscan makehmmerdb; do \
   /usr/bin/install -c -m 0755 $file /usr/local/bin/ ;\
done
make[1]: Leaving directory '/content/hmmer-3.3.2/src'
make -C documentation install
make[1]: Entering directory '/content/hmmer-3.3.2/documentation'
make -C man install
make[2]: Entering directory '/content/hmmer-3.3.2/documentation/man'
for file in hmmer hmmalign hmmbuild hmmc2 hmmconvert hmmemit hmmfetch hmmlogo hmmpgmd hmmpgmd_shard hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer makehmmerdb phmmer nhmmer nhmmscan alimask; do \
   /usr/bin/install -c -m 0664 $file.man /usr/local/share/man/man1/${file}.1 ;\
done
make[2]: Leaving directory '/content/hmmer-3.3.2/documentation/man'
make[1]: Leaving directory '/content/hmmer-3.3.2/documentation'

--2026-06-09 18:12:49--  http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
Resolving eddylab.org (eddylab.org)... 96.126.110.11, 2600:3c03::f03c:91ff:fec8:383c
Connecting to eddylab.org (eddylab.org)|96.126.110.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18213049 (17M) [application/x-gzip]
Saving to: ‘hmmer-3.3.2.tar.gz’

     0K .......... .......... .......... .......... ..........  0%  111K 2m39s
    50K .......... .......... .......... .......... ..........  0%  223K 1m59s
   100K .......... .......... .......... .......... ..........  0%  125M 79s
   150K .......... .......... .......... .......... ..........  1% 37.9M 59s
   200K .......... .......... .......... .......... ..........  1%  224K 63s
   250K .......... .......... .......... .......... ..........  1% 55.0M 52s
   300K .......... .......... .......... .......... ..........  1% 78.0M 45s
   350K .......... .......... .......... .......... ..........  2%  221M 39s
   400K .......... .......... .......... .......... ..........  2%  225K 43s
   450K .......... .......... .......... .......... ..........  2%  119M 39s
   500K .......... .......... .......... .......... ..........  3%  161M 35s
   550K .......... .......... .......... .......... ..........  3% 25.9M 32s
   600K .......... .......... .......... .......... ..........  3% 23.3M 30s
   650K .......... .......... .......... .......... ..........  3%  102M 27s
   700K .......... .......... .......... .......... ..........  4%  160M 26s
   750K .......... .......... .......... .......... ..........  4% 97.0M 24s
   800K .......... .......... .......... .......... ..........  4%  164M 22s
   850K .......... .......... .......... .......... ..........  5%  229K 25s
   900K .......... .......... .......... .......... ..........  5% 60.9M 24s
   950K .......... .......... .......... .......... ..........  5%  324M 23s
  1000K .......... .......... .......... .......... ..........  5%  293M 21s
  1050K .......... .......... .......... .......... ..........  6%  183M 20s
  1100K .......... .......... .......... .......... ..........  6%  280M 19s
  1150K .......... .......... .......... .......... ..........  6% 66.4M 19s
  1200K .......... .......... .......... .......... ..........  7% 35.0M 18s
  1250K .......... .......... .......... .......... ..........  7% 21.6M 17s
  1300K .......... .......... .......... .......... ..........  7% 48.1M 16s
  1350K .......... .......... .......... .......... ..........  7%  101M 16s
  1400K .......... .......... .......... .......... ..........  8%  128M 15s
  1450K .......... .......... .......... .......... ..........  8%  137M 15s
  1500K .......... .......... .......... .......... ..........  8%  247M 14s
  1550K .......... .......... .......... .......... ..........  8%  275M 14s
  1600K .......... .......... .......... .......... ..........  9%  264M 13s
  1650K .......... .......... .......... .......... ..........  9%  301M 13s
  1700K .......... .......... .......... .......... ..........  9%  210M 12s
  1750K .......... .......... .......... .......... .......... 10%  233K 14s
  1800K .......... .......... .......... .......... .......... 10%  110M 14s
  1850K .......... .......... .......... .......... .......... 10%  122M 13s
  1900K .......... .......... .......... .......... .......... 10% 77.8M 13s
  1950K .......... .......... .......... .......... .......... 11%  199M 12s
  2000K .......... .......... .......... .......... .......... 11%  201M 12s
  2050K .......... .......... .......... .......... .......... 11%  120M 12s
  2100K .......... .......... .......... .......... .......... 12%  306M 11s
  2150K .......... .......... .......... .......... .......... 12%  264M 11s
  2200K .......... .......... .......... .......... .......... 12%  268M 11s
  2250K .......... .......... .......... .......... .......... 12%  256M 11s
  2300K .......... .......... .......... .......... .......... 13%  203M 10s
  2350K .......... .......... .......... .......... .......... 13%  307M 10s
  2400K .......... .......... .......... .......... .......... 13%  226M 10s
  2450K .......... .......... .......... .......... .......... 14%  255M 10s
  2500K .......... .......... .......... .......... .......... 14% 93.8M 9s
  2550K .......... .......... .......... .......... .......... 14%  210M 9s
  2600K .......... .......... .......... .......... .......... 14% 22.6M 9s
  2650K .......... .......... .......... .......... .......... 15%  176M 9s
  2700K .......... .......... .......... .......... .......... 15%  140M 9s
  2750K .......... .......... .......... .......... .......... 15%  126M 8s
  2800K .......... .......... .......... .......... .......... 16%  117M 8s
  2850K .......... .......... .......... .......... .......... 16%  154M 8s
  2900K .......... .......... .......... .......... .......... 16%  145M 8s
  2950K .......... .......... .......... .......... .......... 16%  316M 8s
  3000K .......... .......... .......... .......... .......... 17%  258M 8s
  3050K .......... .......... .......... .......... .......... 17%  316M 7s
  3100K .......... .......... .......... .......... .......... 17%  268M 7s
  3150K .......... .......... .......... .......... .......... 17%  266M 7s
  3200K .......... .......... .......... .......... .......... 18%  266M 7s
  3250K .......... .......... .......... .......... .......... 18%  187M 7s
  3300K .......... .......... .......... .......... .......... 18%  318M 7s
  3350K .......... .......... .......... .......... .......... 19%  321M 7s
  3400K .......... .......... .......... .......... .......... 19%  235M 7s
  3450K .......... .......... .......... .......... .......... 19%  296M 6s
  3500K .......... .......... .......... .......... .......... 19%  312M 6s
  3550K .......... .......... .......... .......... .......... 20%  319M 6s
  3600K .......... .......... .......... .......... .......... 20%  234K 7s
  3650K .......... .......... .......... .......... .......... 20%  125M 7s
  3700K .......... .......... .......... .......... .......... 21%  116M 7s
  3750K .......... .......... .......... .......... .......... 21%  156M 7s
  3800K .......... .......... .......... .......... .......... 21%  132M 6s
  3850K .......... .......... .......... .......... .......... 21%  141M 6s
  3900K .......... .......... .......... .......... .......... 22%  112M 6s
  3950K .......... .......... .......... .......... .......... 22%  242M 6s
  4000K .......... .......... .......... .......... .......... 22%  203M 6s
  4050K .......... .......... .......... .......... .......... 23%  304M 6s
  4100K .......... .......... .......... .......... .......... 23%  203M 6s
  4150K .......... .......... .......... .......... .......... 23%  312M 6s
  4200K .......... .......... .......... .......... .......... 23%  256M 6s
  4250K .......... .......... .......... .......... .......... 24%  221M 6s
  4300K .......... .......... .......... .......... .......... 24%  187M 6s
  4350K .......... .......... .......... .......... .......... 24%  197M 5s
  4400K .......... .......... .......... .......... .......... 25%  295M 5s
  4450K .......... .......... .......... .......... .......... 25%  319M 5s
  4500K .......... .......... .......... .......... .......... 25%  274M 5s
  4550K .......... .......... .......... .......... .......... 25%  303M 5s
  4600K .......... .......... .......... .......... .......... 26%  299M 5s
  4650K .......... .......... .......... .......... .......... 26%  284M 5s
  4700K .......... .......... .......... .......... .......... 26%  270M 5s
  4750K .......... .......... .......... .......... .......... 26%  315M 5s
  4800K .......... .......... .......... .......... .......... 27%  189M 5s
  4850K .......... .......... .......... .......... .......... 27%  301M 5s
  4900K .......... .......... .......... .......... .......... 27%  171M 5s
  4950K .......... .......... .......... .......... .......... 28%  169M 5s
  5000K .......... .......... .......... .......... .......... 28%  135M 5s
  5050K .......... .......... .......... .......... .......... 28%  145M 4s
  5100K .......... .......... .......... .......... .......... 28%  147M 4s
  5150K .......... .......... .......... .......... .......... 29%  184M 4s
  5200K .......... .......... .......... .......... .......... 29%  193M 4s
  5250K .......... .......... .......... .......... .......... 29%  186M 4s
  5300K .......... .......... .......... .......... .......... 30%  269M 4s
  5350K .......... .......... .......... .......... .......... 30%  299M 4s
  5400K .......... .......... .......... .......... .......... 30%  304M 4s
  5450K .......... .......... .......... .......... .......... 30%  306M 4s
  5500K .......... .......... .......... .......... .......... 31%  246M 4s
  5550K .......... .......... .......... .......... .......... 31%  312M 4s
  5600K .......... .......... .......... .......... .......... 31%  320M 4s
  5650K .......... .......... .......... .......... .......... 32%  316M 4s
  5700K .......... .......... .......... .......... .......... 32%  261M 4s
  5750K .......... .......... .......... .......... .......... 32%  316M 4s
  5800K .......... .......... .......... .......... .......... 32%  286M 4s
  5850K .......... .......... .......... .......... .......... 33%  329M 4s
  5900K .......... .......... .......... .......... .......... 33%  264M 4s
  5950K .......... .......... .......... .......... .......... 33%  311M 4s
  6000K .......... .......... .......... .......... .......... 34%  308M 4s
  6050K .......... .......... .......... .......... .......... 34%  321M 3s
  6100K .......... .......... .......... .......... .......... 34%  248M 3s
  6150K .......... .......... .......... .......... .......... 34%  318M 3s
  6200K .......... .......... .......... .......... .......... 35%  312M 3s
  6250K .......... .......... .......... .......... .......... 35%  309M 3s
  6300K .......... .......... .......... .......... .......... 35%  235K 4s
  6350K .......... .......... .......... .......... .......... 35%  190M 4s
  6400K .......... .......... .......... .......... .......... 36%  112M 4s
  6450K .......... .......... .......... .......... .......... 36%  168M 4s
  6500K .......... .......... .......... .......... .......... 36%  151M 3s
  6550K .......... .......... .......... .......... .......... 37%  143M 3s
  6600K .......... .......... .......... .......... .......... 37%  134M 3s
  6650K .......... .......... .......... .......... .......... 37%  193M 3s
  6700K .......... .......... .......... .......... .......... 37%  237M 3s
  6750K .......... .......... .......... .......... .......... 38%  275M 3s
  6800K .......... .......... .......... .......... .......... 38%  269M 3s
  6850K .......... .......... .......... .......... .......... 38%  318M 3s
  6900K .......... .......... .......... .......... .......... 39%  305M 3s
  6950K .......... .......... .......... .......... .......... 39%  298M 3s
  7000K .......... .......... .......... .......... .......... 39%  229M 3s
  7050K .......... .......... .......... .......... .......... 39%  272M 3s
  7100K .......... .......... .......... .......... .......... 40%  317M 3s
  7150K .......... .......... .......... .......... .......... 40%  317M 3s
  7200K .......... .......... .......... .......... .......... 40%  247M 3s
  7250K .......... .......... .......... .......... .......... 41%  309M 3s
  7300K .......... .......... .......... .......... .......... 41%  282M 3s
  7350K .......... .......... .......... .......... .......... 41%  304M 3s
  7400K .......... .......... .......... .......... .......... 41%  226K 3s
  7450K .......... .......... .......... .......... .......... 42%  100M 3s
  7500K .......... .......... .......... .......... .......... 42%  162M 3s
  7550K .......... .......... .......... .......... .......... 42%  318M 3s
  7600K .......... .......... .......... .......... .......... 43%  313M 3s
  7650K .......... .......... .......... .......... .......... 43%  304M 3s
  7700K .......... .......... .......... .......... .......... 43%  206M 3s
  7750K .......... .......... .......... .......... .......... 43%  234M 3s
  7800K .......... .......... .......... .......... .......... 44%  247M 3s
  7850K .......... .......... .......... .......... .......... 44%  306M 3s
  7900K .......... .......... .......... .......... .......... 44%  276M 3s
  7950K .......... .......... .......... .......... .......... 44% 14.7M 3s
  8000K .......... .......... .......... .......... .......... 45%  311M 3s
  8050K .......... .......... .......... .......... .......... 45%  321M 3s
  8100K .......... .......... .......... .......... .......... 45%  342M 3s
  8150K .......... .......... .......... .......... .......... 46%  272M 3s
  8200K .......... .......... .......... .......... .......... 46%  311M 3s
  8250K .......... .......... .......... .......... .......... 46%  328M 3s
  8300K .......... .......... .......... .......... .......... 46%  319M 3s
  8350K .......... .......... .......... .......... .......... 47%  248M 3s
  8400K .......... .......... .......... .......... .......... 47%  332M 2s
  8450K .......... .......... .......... .......... .......... 47%  255M 2s
  8500K .......... .......... .......... .......... .......... 48%  299M 2s
  8550K .......... .......... .......... .......... .......... 48%  276M 2s
  8600K .......... .......... .......... .......... .......... 48%  321M 2s
  8650K .......... .......... .......... .......... .......... 48%  292M 2s
  8700K .......... .......... .......... .......... .......... 49%  337M 2s
  8750K .......... .......... .......... .......... .......... 49%  254M 2s
  8800K .......... .......... .......... .......... .......... 49%  307M 2s
  8850K .......... .......... .......... .......... .......... 50%  323M 2s
  8900K .......... .......... .......... .......... .......... 50%  325M 2s
  8950K .......... .......... .......... .......... .......... 50%  252M 2s
  9000K .......... .......... .......... .......... .......... 50%  328M 2s
  9050K .......... .......... .......... .......... .......... 51%  326M 2s
  9100K .......... .......... .......... .......... .......... 51%  303M 2s
  9150K .......... .......... .......... .......... .......... 51%  261M 2s
  9200K .......... .......... .......... .......... .......... 52%  266M 2s
  9250K .......... .......... .......... .......... .......... 52%  292M 2s
  9300K .......... .......... .......... .......... .......... 52% 31.5M 2s
  9350K .......... .......... .......... .......... .......... 52%  346M 2s
  9400K .......... .......... .......... .......... .......... 53%  271M 2s
  9450K .......... .......... .......... .......... .......... 53%  236K 2s
  9500K .......... .......... .......... .......... .......... 53%  289M 2s
  9550K .......... .......... .......... .......... .......... 53%  354M 2s
  9600K .......... .......... .......... .......... .......... 54%  378M 2s
  9650K .......... .......... .......... .......... .......... 54%  346M 2s
  9700K .......... .......... .......... .......... .......... 54%  303M 2s
  9750K .......... .......... .......... .......... .......... 55%  192M 2s
  9800K .......... .......... .......... .......... .......... 55%  170M 2s
  9850K .......... .......... .......... .......... .......... 55%  140M 2s
  9900K .......... .......... .......... .......... .......... 55%  175M 2s
  9950K .......... .......... .......... .......... .......... 56%  132M 2s
 10000K .......... .......... .......... .......... .......... 56%  223M 2s
 10050K .......... .......... .......... .......... .......... 56%  123M 2s
 10100K .......... .......... .......... .......... .......... 57%  122M 2s
 10150K .......... .......... .......... .......... .......... 57%  197M 2s
 10200K .......... .......... .......... .......... .......... 57%  237M 2s
 10250K .......... .......... .......... .......... .......... 57%  303M 2s
 10300K .......... .......... .......... .......... .......... 58%  266M 2s
 10350K .......... .......... .......... .......... .......... 58%  347M 2s
 10400K .......... .......... .......... .......... .......... 58%  290M 2s
 10450K .......... .......... .......... .......... .......... 59%  281M 2s
 10500K .......... .......... .......... .......... .......... 59%  254M 2s
 10550K .......... .......... .......... .......... .......... 59%  293M 2s
 10600K .......... .......... .......... .......... .......... 59%  247M 2s
 10650K .......... .......... .......... .......... .......... 60%  297M 2s
 10700K .......... .......... .......... .......... .......... 60%  259M 2s
 10750K .......... .......... .......... .......... .......... 60%  190M 2s
 10800K .......... .......... .......... .......... .......... 61%  143M 2s
 10850K .......... .......... .......... .......... .......... 61%  140M 2s
 10900K .......... .......... .......... .......... .......... 61%  119M 2s
 10950K .......... .......... .......... .......... .......... 61%  252M 2s
 11000K .......... .......... .......... .......... .......... 62%  316M 2s
 11050K .......... .......... .......... .......... .......... 62%  203M 1s
 11100K .......... .......... .......... .......... .......... 62%  171M 1s
 11150K .......... .......... .......... .......... .......... 62%  319M 1s
 11200K .......... .......... .......... .......... .......... 63%  239M 1s
 11250K .......... .......... .......... .......... .......... 63%  277M 1s
 11300K .......... .......... .......... .......... .......... 63%  217M 1s
 11350K .......... .......... .......... .......... .......... 64%  241M 1s
 11400K .......... .......... .......... .......... .......... 64%  230M 1s
 11450K .......... .......... .......... .......... .......... 64%  230M 1s
 11500K .......... .......... .......... .......... .......... 64%  205M 1s
 11550K .......... .......... .......... .......... .......... 65%  250M 1s
 11600K .......... .......... .......... .......... .......... 65%  228M 1s
 11650K .......... .......... .......... .......... .......... 65%  267M 1s
 11700K .......... .......... .......... .......... .......... 66%  230M 1s
 11750K .......... .......... .......... .......... .......... 66%  338M 1s
 11800K .......... .......... .......... .......... .......... 66% 36.4M 1s
 11850K .......... .......... .......... .......... .......... 66%  277M 1s
 11900K .......... .......... .......... .......... .......... 67% 14.8M 1s
 11950K .......... .......... .......... .......... .......... 67%  161M 1s
 12000K .......... .......... .......... .......... .......... 67%  179M 1s
 12050K .......... .......... .......... .......... .......... 68%  226M 1s
 12100K .......... .......... .......... .......... .......... 68%  151M 1s
 12150K .......... .......... .......... .......... .......... 68%  173M 1s
 12200K .......... .......... .......... .......... .......... 68%  280M 1s
 12250K .......... .......... .......... .......... .......... 69%  407M 1s
 12300K .......... .......... .......... .......... .......... 69%  374M 1s
 12350K .......... .......... .......... .......... .......... 69%  261M 1s
 12400K .......... .......... .......... .......... .......... 69%  291M 1s
 12450K .......... .......... .......... .......... .......... 70%  286M 1s
 12500K .......... .......... .......... .......... .......... 70%  282M 1s
 12550K .......... .......... .......... .......... .......... 70%  259M 1s
 12600K .......... .......... .......... .......... .......... 71%  263M 1s
 12650K .......... .......... .......... .......... .......... 71%  302M 1s
 12700K .......... .......... .......... .......... .......... 71%  292M 1s
 12750K .......... .......... .......... .......... .......... 71%  243K 1s
 12800K .......... .......... .......... .......... .......... 72%  150M 1s

In [6]:
!wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz

--2026-06-09 18:14:22--  http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 293000230 (279M) [application/x-gzip]
Saving to: ‘Pfam-A.hmm.gz’

Pfam-A.hmm.gz       100%[===================>] 279.43M  3.49MB/s    in 6m 8s

2026-06-09 18:20:31 (778 KB/s) - ‘Pfam-A.hmm.gz’ saved [293000230/293000230]

In [7]:
!gunzip Pfam-A.hmm.gz

In [8]:
!hmmpress Pfam-A.hmm

Working...    done.
Pressed and indexed 19632 HMMs (19632 names and 19632 accessions).
Models pressed into binary file:   Pfam-A.hmm.h3m
SSI index for binary model file:   Pfam-A.hmm.h3i
Profiles (MSV part) pressed into:  Pfam-A.hmm.h3f
Profiles (remainder) pressed into: Pfam-A.hmm.h3p

In [9]:
!head -n 40 Pfam-A.hmm

HMMER3/f [3.1b2 | February 2015]
NAME  1-cysPrx_C
ACC   PF10417.12
DESC  C-terminal domain of 1-Cys peroxiredoxin
LENG  40
ALPH  amino
RF    no
MM    no
CONS  yes
CS    yes
MAP   yes
DATE  Thu Nov  4 19:20:02 2021
NSEQ  40
EFFN  17.426758
CKSUM 4086680297
GA    21.1 21.1;
TC    21.1 21.1;
NC    21 21;
BM    hmmbuild HMM.ann SEED.ann
SM    hmmsearch -Z 61295632 -E 1000 --cpu 4 HMM pfamseq
STATS LOCAL MSV       -7.5463  0.71948
STATS LOCAL VITERBI   -7.8624  0.71948
STATS LOCAL FORWARD   -4.3303  0.71948
HMM          A        C        D        E        F        G        H        I        K        L        M        N        P        Q        R        S        T        V        W        Y
            m->m     m->i     m->d     i->m     i->i     d->m     d->d
  COMPO   2.28046  4.31208  2.83393  2.63913  3.90855  2.69988  3.89812  3.33401  2.56310  2.85023  3.99954  3.22924  2.52123  2.90328  3.31238  2.94055  2.70512  2.59551  3.49266  3.82715
          2.68618  4.42225  2.77519  2.73123  3.46354  2.40513  3.72494  3.29354  2.67741  2.69355  4.24690  2.90347  2.73739  3.18146  2.89801  2.37887  2.77519  2.98518  4.58477  3.61503
          0.00226  6.48754  7.20989  0.61958  0.77255  0.00000        *
      1   0.29666  6.14436  6.78514  6.79783  7.06332  2.55785  7.22049  6.57837  6.66651  6.27638  3.28757  5.91223  5.83978  6.69238  6.58162  2.20136  4.83343  5.59959  8.41086  7.43107      1 A - - H
          2.68618  4.42225  2.77519  2.73123  3.46354  2.40513  3.72494  3.29354  2.67741  2.69355  4.24690  2.90347  2.73739  3.18146  2.89801  2.37887  2.77519  2.98518  4.58477  3.61503
          0.00226  6.48754  7.20989  0.61958  0.77255  0.48576  0.95510
      2   4.59591  5.92009  6.57211  5.96147  1.92899  5.81035  6.10135  2.33093  5.75927  0.69439  2.86149  5.97820  6.07717  5.78793  5.72916  5.13924  4.81708  2.59612  3.18569  3.35842      2 l - - H
          2.68618  4.42225  2.77519  2.73123  3.46354  2.40513  3.72494  3.29354  2.67741  2.69355  4.24690  2.90347  2.73739  3.18146  2.89801  2.37887  2.77519  2.98518  4.58477  3.61503
          0.00226  6.48754  7.20989  0.61958  0.77255  0.48576  0.95510
      3   4.81290  7.05274  3.71696  4.47757  6.60126  5.41623  3.72993  5.92180  2.06538  3.59487  6.10993  4.89014  5.75663  0.42291  2.54802  4.76779  4.95656  5.56452  7.24472  6.08615      3 Q - - H
          2.68618  4.42225  2.77519  2.73123  3.46354  2.40513  3.72494  3.29354  2.67741  2.69355  4.24690  2.90347  2.73739  3.18146  2.89801  2.37887  2.77519  2.98518  4.58477  3.61503
          0.00226  6.48754  7.20989  0.61958  0.77255  0.48576  0.95510
      4   2.64100  5.28125  5.84007  3.33362  1.80025  5.06896  2.72827  3.71332  5.01717  1.75203  2.65498  5.22280  5.43290  5.15329  5.03455  4.37913  1.80041  2.31249  5.90246  2.63298      4 l - - H
          2.68618  4.42225  2.77519  2.73123  3.46354  2.40513  3.72494  3.29354  2.67741  2.69355  4.24690  2.90347  2.73739  3.18146  2.89801  2.37887  2.77519  2.98518  4.58477  3.61503
          0.00226  6.48754  7.20989  0.61958  0.77255  0.48576  0.95510

In [10]:
!hmmstat Pfam-A.hmm.h3m | head -n 20

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      1-cysPrx_C           PF10417.12         40    17.43     40   1.37   1.32   1.29   0.09
2      120_Rick_ant         PF12574.11          2     0.45    238   0.59   0.60   0.52   0.02
3      12TM_1               PF09847.12          7     2.28    449   0.59   0.62   0.51   0.09
4      14-3-3               PF00244.23        149     2.50    222   0.59   0.59   0.52   0.05
5      17kDa_Anti_2         PF16998.8           6     0.99    116   0.59   0.57   0.52   0.03
6      2-Hacid_dh           PF00389.33         78     5.69    134   0.59   0.62   0.44   0.03
7      2-Hacid_dh_C         PF02826.22        135     3.55    178   0.59   0.60   0.53   0.01
8      2-oxoacid_dh         PF00198.26         70     3.33    233   0.59   0.61   0.53   0.02
9      2-oxogl_dehyd_N      PF16078.8         208    11.82     41   1.34   1.23   1.33   0.13
10     2-ph_phosp           PF04029.17        125     3.02    226   0.59   0.62   0.51   0.02
11     2-thiour_desulf      PF04463.15        338     2.11    137   0.59   0.57   0.46   0.02
12     23ISL                PF16620.8          16     1.48    162   0.59   0.61   0.54   0.07

In [11]:
!hmmfetch --index Pfam-A.hmm.h3m

Working...    done.
Indexed 19632 HMMs (19632 names and 19632 accessions).
SSI index written to file Pfam-A.hmm.h3m.ssi

# Выбор и анализ 10 семейств

Выбрал следующие: ALKBH1, BAP1, HDAC11, EEF1AKMT4, SUDS3, SIRT2, ZNHIT1, SAP18, PRMT8, TDG

# 1) ALKBH1

In [12]:
!hmmfetch Pfam-A.hmm.h3m PF13532.9 > alkbh1.hmm

In [13]:
!grep PF13532 Pfam-A.hmm

ACC   PF13532.9

In [14]:
!hmmstat alkbh1.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      2OG-FeII_Oxy_2       PF13532.9          36     4.21    194   0.59   0.55   0.47   0.02

In [15]:
!hmmsearch alkbh1.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  alkbh1.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       2OG-FeII_Oxy_2  [M=194]
Accession:   PF13532.9
Description: 2OG-Fe(II) oxygenase superfamily
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    4.2e-23   83.2   0.0    8.4e-23   82.2   0.0    1.5  1  gene=LOC118508064  scaffold=NC_050202.1 strand=+ Parent=rna-X
      2e-14   54.9   0.0    3.2e-13   51.0   0.0    1.9  2  gene=LOC118502523  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.4e-12   48.9   0.0    1.2e-11   45.8   0.0    1.9  1  gene=LOC118516394  scaffold=NW_023405219.1 strand=+ Parent=rn


Domain annotation for each sequence (and alignments):
>> gene=LOC118508064  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036047522.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   82.2   0.0   8.5e-27   8.4e-23      18     194 .]     140     323 ..     135     323 .. 0.80

  Alignments for each domain:
  == domain 1  score: 82.2 bits;  conditional E-value: 8.5e-27
     2OG-FeII_Oxy_2  18 lkelleegpfrqptilggkrvsvqqtlcgtlrwat.dgpkyrysekrsvkskpf.spfpeallqlverlvkeag.peglspnaalvnfYsdg 106
                        ++e++e++     ++   ++ ++q +   + r++   g++  y + +++k kp+ +++p++  +l++rl +    ++ + p+++ vn+Y++g
  gene=LOC118508064 140 IDEAMEKVLLEAVNCDDSEATDLQFKKTLKHRKVKhFGYEFVYGTNNVDKTKPLeRKIPAVCDELWKRLQNLHPeLRWHVPDQLTVNHYDPG 231
                        566666666666667766676776643333333330347777887766666666368999999******986655677789*********** PP

     2OG-FeII_Oxy_2 107 ariglHqDkeesalgapivSlSLGasatflfgtesreeeiiallLesgdllvmggesrkay.Hgvprikkdtapeq.....selesrRinlT 192
                        + i  H+D  ++ +++pi+SlSLG+ +++ f++   + ++  + L+  +ll+mggesr+ + Hg+++ k dt p +      + ++ R++lT
  gene=LOC118508064 232 QGIPPHVDTHSA-FDDPILSLSLGSDVVMEFKQP-FSGKQVCVDLPARSLLIMGGESRYDWtHGITPRKMDTVPASnggltVRKRKLRVSLT 321
                        **********88.*******************97.55567779****************************999999999966699****** PP

     2OG-FeII_Oxy_2 193 fR 194
                        fR
  gene=LOC118508064 322 FR 323
                        *9 PP

>> gene=LOC118502523  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036034788.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    2.6   0.0     0.022   2.1e+02       2      28 ..      15      43 ..      14      53 .. 0.79
   2 !   51.0   0.0   3.2e-17   3.2e-13      58     194 .]      52     213 ..      38     213 .. 0.85

  Alignments for each domain:
  == domain 1  score: 2.6 bits;  conditional E-value: 0.022
     2OG-FeII_Oxy_2  2 lllipnflseeeaaellkelleegp..fr 28
                       ++++p+f+++ee  +++++++++ +  ++
  gene=LOC118502523 15 VYYVPDFITKEEECSIMQAIDKTPKprWT 43
                       89****************99955442344 PP

  == domain 2  score: 51.0 bits;  conditional E-value: 3.2e-17
     2OG-FeII_Oxy_2  58 rysekrsvkskpfspfpeallqlverlvkeag.peglspnaalvnfYsdgariglHqDkeesalgapivSlSLGasatflfgtesree.... 144
                        +y ++ + k+  ++++p+ l++ +er+ +     +g ++n++l+n Y +g+ i+ H D     + ++i ++S G+ a++ + +++++
  gene=LOC118502523  52 NYGGVPHPKGMIAEDIPAWLTRYIERVNQLNVyEDGIKANHVLINEYLPGQGIMPHLDGP-L-FYPTITTISCGSHAVLEYYDQTEDSesps 141
                        566666667777899************997774559***********************9.3.78****************98876666899 PP

     2OG-FeII_Oxy_2 145 .......eiiallLesgdllvmggesrkay.Hgvprikkdtapeq..............selesrRinlTfR 194
                                +  + Le+ +ll+ + ++ + y H+++  ++d  +                   +++Ri+lT+R
  gene=LOC118502523 142 ngplvrhHVANIVLEPRSLLIVKDDMYHKYlHAIAELEQDVIDDKaanlsmlnsvsvgdVLQRTKRISLTIR 213
                        9*****99********************************44444455566777778885669*******99 PP

>> gene=LOC118516394  scaffold=NW_023405219.1 strand=+ Parent=rna-XM_036062255.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   45.8   0.0   1.3e-15   1.2e-11      55     194 .]      49     212 ..      14     212 .. 0.83

  Alignments for each domain:
  == domain 1  score: 45.8 bits;  conditional E-value: 1.3e-15
     2OG-FeII_Oxy_2  55 pkyrysekrsvkskpfspfpeallqlverlvkeag.peglspnaalvnfYsdgariglHqDkeesalgapivSlSLGasatflfgtesree. 144
                        +  +y ++ + k+  ++++p+ l++ +er+ +     +g ++n++l+n Y +g+ i+ H D     l  p  ++S G+ a++ + +++++
  gene=LOC118516394  49 RLINYGGVPHPKGMIAEDIPAWLTRYIERVNQLNVyEDGIKANHVLINEYLPGQGIMPHLDGP---LFYPTTTISCGSHAVLEYYDQTEDSe 137
                        55577777777888899*************997774559***********************9...44799*************98876666 PP

     2OG-FeII_Oxy_2 145 ..........eiiallLesgdllvmggesrkay.Hgvprikkdtapeq..............selesrRinlTfR 194
                                   +  + Le+ +ll+ + ++ + y H+++  ++d  +                   +++Ri+lT+R
  gene=LOC118516394 138 spsngplvrhHVANIVLEPRSLLIVKDDMYHKYlHAIAELEQDVIDDKaanlsmlnsvsvgdVLQRTKRISLTIR 212
                        8999*****99********************************44444455566777778885669*******99 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (194 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1311  (0.0442009); expected 593.2 (0.02)
Passed bias filter:                      407  (0.0137222); expected 593.2 (0.02)
Passed Vit filter:                        35  (0.00118004); expected 29.7 (0.001)
Passed Fwd filter:                        10  (0.000337154); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               3  [number of targets reported over threshold]
# CPU time: 0.56u 0.01s 00:00:00.57 Elapsed: 00:00:00.33
# Mc/sec: 7650.20
//
[ok]

# 2) BAP1

In [16]:
!grep PF01088 Pfam-A.hmm

ACC   PF01088.24

In [17]:
!hmmfetch Pfam-A.hmm.h3m PF01088.24 > bap1.hmm
!hmmstat bap1.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      Peptidase_C12        PF01088.24        349     2.96    211   0.59   0.57   0.44   0.02

In [18]:
!hmmsearch bap1.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  bap1.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Peptidase_C12  [M=211]
Accession:   PF01088.24
Description: Ubiquitin carboxyl-terminal hydrolase, family 1
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    8.3e-70  235.5   0.0    1.3e-69  234.9   0.0    1.3  1  gene=LOC118512888  scaffold=NC_050203.1 strand=+ Parent=rna-X
      7e-66  222.7   0.0    1.6e-65  221.5   0.0    1.7  1  gene=LOC118508022  scaffold=NC_050202.1 strand=- Parent=rna-X
    2.1e-42  146.0   0.4    2.3e-42  145.9   0.4    1.0  1  gene=LOC118503994  scaffold=NC_050202.1 strand=- Parent=rna-X
  ------ inclusion threshold ------
      0.038   14.4   0.0      0.058   13.9   0.0    1.2  1  gene=LOC118510116  scaffold=NC_050203.1 strand=+ Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118512888  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036057987.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  234.9   0.0   1.8e-73   1.3e-69       1     210 [.       8     208 ..       8     209 .. 0.91

  Alignments for each domain:
  == domain 1  score: 234.9 bits;  conditional E-value: 1.8e-73
                        ---EE--HHHHHHHHHHHT--S..EEEE--S.SHHHTTS.---EEEEEEE.----------.---------..T...TS------STTGHHH CS
      Peptidase_C12   1 wlplEsdpevftelleklGvkgvqfeevyslddellasl.pvygliflfkyieeeeeeekrekeeeekdeeeeevsekvfFakQtiqnaCgt 91
                        w+ +Esdp+vftel++++Gv+gvq+ee++sld+++++ l pv+gl+flfk+++++ e + +  +    d    +  ek+fFakQ+i+naC+t
  gene=LOC118512888   8 WCLIESDPGVFTELIKEFGVDGVQVEELWSLDEDSFKDLePVHGLVFLFKWVKDD-EPAGSIVQ----D----SRLEKIFFAKQVINNACAT 90
                        *******************************999*999988***********988.44433222....2....23567************** PP

                        HHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHH...HHS--EEEEEEEEETTEEEEE-T CS
      Peptidase_C12  92 iAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapee...eedvafHFiafvpvdgrlyeLDG 180
                        +A+L++llN  +++++i+lg +L++fkef+ ++++ ++g al+n ++ir++hnsfa+++  e +++   +ed  fHF+ +vpvdgrlyeLDG
  gene=LOC118512888  91 QAILSILLN--ATHSDINLGATLTDFKEFACTFDAYNKGLALSNASQIRTVHNSFARQTLFELDNKssgKED-VFHFVGYVPVDGRLYELDG 179
                        *********..568999***************************************9888777766777778.8****************** PP

                        TS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 181 lkegPidlgeleeeeedledavrkviqeri 210
                        lkegPid+g++  +++d+ ++vr++i++r+
  gene=LOC118512888 180 LKEGPIDHGAV-GSGQDWLKVVRPIIEKRM 208
                        ***********.578*************98 PP

>> gene=LOC118508022  scaffold=NC_050202.1 strand=- Parent=rna-XM_036047414.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  221.5   0.0   2.2e-69   1.6e-65       1     210 [.      12     221 ..      12     222 .. 0.87

  Alignments for each domain:
  == domain 1  score: 221.5 bits;  conditional E-value: 2.2e-69
                        ---EE--HHHHHHHHHHHT--S..EEEE--S.SHHHTTS---EEEEEEE.----------.-----.----..T...TS------STTGHHH CS
      Peptidase_C12   1 wlplEsdpevftelleklGvkgvqfeevyslddellaslpvygliflfkyieeeeeeekrekeeee.kdeeeeevsekvfFakQtiqnaCgt 91
                        wl+lEsdp++ft l+e++Gvkgvq+ee+y+l++  l+  +vyg+iflf++iee++ ++k   e+++ + ++e+   +++fFa+Q+++n+C+t
  gene=LOC118508022  12 WLELESDPGLFTLLMEDFGVKGVQVEEIYDLQK-NLEG-QVYGFIFLFRWIEERRARRKI-VETTDiYVKDEDA-VNNIFFAQQVVPNSCAT 99
                        9******************************54.4433.6************99888876.4444444444334.557************** PP

                        HHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHH.........HHS--EEEEEEEEETTE CS
      Peptidase_C12  92 iAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapee.........eedvafHFiafvpvdgr 174
                        +AlL+vllN++    +ielg +L+++k +tkg+spe++g a++n++e++ ahns+a ++  +  ++         + + afHF++fvp+dgr
  gene=LOC118508022 100 HALLSVLLNCS----DIELGLTLSRLKMHTKGMSPENKGWAIGNTPELACAHNSHAMPQARRRMDRnsgvstgrfTGE-AFHFVSFVPIDGR 186
                        *********99....89***************************************7665544444678888887667.9************ PP

                        EEEE-TTS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 175 lyeLDGlkegPidlgeleeeeedledavrkviqeri 210
                        l+eLDGlk++P+d+g++  e+e ++d++r+v+ +r+
  gene=LOC118508022 187 LFELDGLKPFPMDHGPW-GEKEAWTDKFRRVMSDRL 221
                        *****************.4679*********99885 PP

>> gene=LOC118503994  scaffold=NC_050202.1 strand=- Parent=rna-XM_036037962.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  145.9   0.4   3.1e-46   2.3e-42      60     210 ..       5     151 ..       1     152 [. 0.87

  Alignments for each domain:
  == domain 1  score: 145.9 bits;  conditional E-value: 3.1e-46
                        -.---------..T...TS------STTGHHHHHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..-- CS
      Peptidase_C12  60 rekeeeekdeeeeevsekvfFakQtiqnaCgtiAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegq 151
                        r+ke+ee + ++ e+ +++fF +Q ++naCgtiA++h++lN  n + eie+gs+Lkk+++ +k+lsp++rge+l+++  ++ +h++ a+egq
  gene=LOC118503994   5 RAKEDEELKAKNVEHPKSLFFTRQFVHNACGTIAVIHAILN--NPDIEIEEGSVLKKYFDGAKDLSPDDRGELLNKNVDLKATHEENAQEGQ 94
                        223444433334556789***********************..557888******************************************* PP

                        -SSTHHHHS--EEEEEEEEETTEEEEE-TTS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 152 teapeeeedvafHFiafvpvdgrlyeLDGlkegPidlgeleeeeedledavrkviqeri 210
                        t++p+ ++ v +HFiafv+v+g+lyeLDG+k++P+ +g++++  e+l + + +v++++i
  gene=LOC118503994  95 TATPNINDAVYHHFIAFVEVEGTLYELDGRKNFPVAHGKTTP--ETLLKDAVQVCKKFI 151
                        ****999999******************************65..67866668****998 PP

>> gene=LOC118510116  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036051583.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   13.9   0.0   7.8e-06     0.058     100     164 ..      31      90 ..      18      95 .. 0.80

  Alignments for each domain:
  == domain 1  score: 13.9 bits;  conditional E-value: 7.8e-06
                        H..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHHHHS--EE CS
      Peptidase_C12 100 NleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapeeeedvafH 164
                        +++    ++e  + ++++ e++++++ ++r+ ++e+  ++++ h+++ + + ++ap+ e++  +H
  gene=LOC118510116  31 ECD---LDLEDPNIISRLPEQCQNVDDATRALMVEEAASFKQFHQKLLDYEASQAPATEDE--VH 90
                        544...456778899*********************************9999999977554..44 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (211 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1609  (0.0542481); expected 593.2 (0.02)
Passed bias filter:                      583  (0.0196561); expected 593.2 (0.02)
Passed Vit filter:                        35  (0.00118004); expected 29.7 (0.001)
Passed Fwd filter:                         4  (0.000134862); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               4  [number of targets reported over threshold]
# CPU time: 0.51u 0.01s 00:00:00.52 Elapsed: 00:00:00.27
# Mc/sec: 10124.24
//
[ok]

# 3) HDAC11

In [19]:
!grep PF00850 Pfam-A.hmm

ACC   PF00850.22

In [20]:
!hmmfetch Pfam-A.hmm.h3m PF00850.22 > HDAC11.hmm
!hmmstat HDAC11.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      Hist_deacetyl        PF00850.22         68     2.85    307   0.59   0.57   0.48   0.02

In [21]:
!hmmsearch HDAC11.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  HDAC11.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Hist_deacetyl  [M=307]
Accession:   PF00850.22
Description: Histone deacetylase domain
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    6.2e-89  299.1   0.1    8.1e-89  298.7   0.1    1.1  1  gene=LOC118511268  scaffold=NC_050203.1 strand=+ Parent=rna-X
    2.7e-88  297.0   0.4    3.4e-88  296.7   0.4    1.1  1  gene=LOC118517556  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.1e-82  278.6   0.0    1.1e-82  278.6   0.0    2.3  3  gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-X
    1.2e-82  278.5   0.0    1.2e-82  278.5   0.0    2.3  2  gene=LOC118510456  scaffold=NC_050201.1 strand=+ Parent=rna-X
    1.2e-82  278.5   0.0    1.2e-82  278.5   0.0    2.3  2  gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-X
    4.7e-54  184.6   0.0    5.9e-54  184.2   0.0    1.1  1  gene=LOC118505081  scaffold=NC_050202.1 strand=+ Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118511268  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036051029.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  298.7   0.1   1.6e-92   8.1e-89       1     305 [.      26     315 ..      26     317 .. 0.93

  Alignments for each domain:
  == domain 1  score: 298.7 bits;  conditional E-value: 1.6e-92
                        SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCCCCSSSCHCTSTCCHHHHH CS
      Hist_deacetyl   1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskseskedddtylspgsleaakl 92
                        hp++p+R++ ++++l  ++gl +k+e+ ++p++at +e++++Hs++Y+++l++   +  ++ +++   +++ +    +d+++++g++e+++l
  gene=LOC118511268  26 HPMKPHRIR-MTHNLLLNYGLYRKMEI-YRPHKATADEMTKFHSDDYIRFLRSIRPDNMSEYNKH---MQRFN--VGEDCPVFDGLYEFCQL 110
                        9********.666666668***99885.************************9887766665333...33333..4678************* PP

                        HHHHHHHHHHHHHTTSSSEEEETT.SS--TT-BSSB-BTTBSS-HHHHHHHHHHHTTTSS-EEEEE-SSS--HHHHHHCTT-SSEEEEEEEE CS
      Hist_deacetyl  93 aagavleavdavlegevrsafalv.rPpgHHAekdkasGFCllNnvaiaakylqkkyglkrvaivDfDvHhGnGtqeifysdpsvltlSiHr 183
                        +ag++++a+ ++ ++   s+++++  +++HHA+k++asGFC++N++++++ +l k y ++rv+++D+DvHhG+G++e+fy +++v+t+S+H+
  gene=LOC118511268 111 SAGGSVAAAVKLNKQ--ASEICINwGGGLHHAKKSEASGFCYVNDIVLGILELLK-Y-HQRVLYIDIDVHHGDGVEEAFYTTDRVMTVSFHK 198
                        *************99..999****9****************************99.4.58******************************** PP

                        -TTTSTTCCGSTT---SGGGTTSEEEEEESST-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTSTTTSBBB-HHHHHHHHHHHHHH CS
      Hist_deacetyl 184 yeesfyPgtgsleeigegkgkgktvnvplekgttdeeylkafeeillpaleefkPelivvsaGfDalkgDplgelnltaegyaeitkkllel 275
                        y ++++Pgtg+l++ig+g+gk ++vn+pl++g++de+y ++f  i+ +++e f+P+++v+++G+D+l gD+lg +nlt++g+ ++++++++
  gene=LOC118511268 199 Y-GEYFPGTGDLRDIGAGRGKYYAVNIPLRDGMDDESYDSIFVPIISKVMETFQPSAVVLQCGADSLTGDRLGCFNLTVKGHGKCVEFVKKY 289
                        9.559************************************************************************************999 PP

                        CGS..C-EEEEEECESSHHHHHHHHHHHHH CS
      Hist_deacetyl 276 aekvskrlvllleGGYnlealarsvtavla 305
                        +     +++++++GGY++++++r++t+ ++
  gene=LOC118511268 290 NL----PFLMVGGGGYTIRNVSRCWTYETS 315
                        98....89******************9986 PP

>> gene=LOC118517556  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036063805.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  296.7   0.4   6.9e-92   3.4e-88       1     305 [.      23     313 ..      23     315 .. 0.95

  Alignments for each domain:
  == domain 1  score: 296.7 bits;  conditional E-value: 6.9e-92
                        SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCCCCSSSCHCTSTCCHHHHH CS
      Hist_deacetyl   1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskseskedddtylspgsleaakl 92
                        hp++p+Rls ++++l  ++gl +k++ i++p +a+ +++ r+Hs+eY+e+l+++t +  +  ++ + +++       dd+++++g++e++ +
  gene=LOC118517556  23 HPMKPHRLS-VIHHLVMNYGLHKKMQ-IYRPYKASAHDMCRFHSDEYIEFLQRVTPQNIQGYTKCLSVFN-----VGDDCPVFDGLFEFCAM 107
                        9********.999999999**98766.6*************************99988777754444443.....4688************* PP

                        HHHHHHHHHHHHHTTSSSEEEETT.SS--TT-BSSB-BTTBSS-HHHHHHHHHHHTTTSS-EEEEE-SSS--HHHHHHCTT-SSEEEEEEEE CS
      Hist_deacetyl  93 aagavleavdavlegevrsafalv.rPpgHHAekdkasGFCllNnvaiaakylqkkyglkrvaivDfDvHhGnGtqeifysdpsvltlSiHr 183
                        ++ga+le+++++ ++  +s+++++  +++HHA+k +asGFC++N+++i++ +l k y + rv+++D+DvHhG+G+qe+fy +++v+t+S+H+
  gene=LOC118517556 108 YTGASLEGAQKLNHN--HSDICINwSGGLHHAKKFEASGFCYVNDIVIGILELLK-Y-HPRVLYIDIDVHHGDGVQEAFYLTDRVMTVSFHK 195
                        *************99..9***********************************99.4.48******************************** PP

                        -TTTSTTCCGSTT---SGGGTTSEEEEEESST-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTSTTTSBBB-HHHHHHHHHHHHHH CS
      Hist_deacetyl 184 yeesfyPgtgsleeigegkgkgktvnvplekgttdeeylkafeeillpaleefkPelivvsaGfDalkgDplgelnltaegyaeitkkllel 275
                        y + f+Pgtg++ eig+++g+ + vnvpl++g++d++y+++f+ ++  ++e ++P +iv+++G+D+l+gD+lg ++l+++g+ e++k++++l
  gene=LOC118517556 196 YGNYFFPGTGDMYEIGAESGRYYSVNVPLKEGIDDQSYVQVFKPVISAVMEFYQPTAIVLQCGADSLAGDRLGCFSLSTKGHGECVKFVKDL 287
                        ******************************************************************************************** PP

                        CGS..C-EEEEEECESSHHHHHHHHHHHHH CS
      Hist_deacetyl 276 aekvskrlvllleGGYnlealarsvtavla 305
                        +     +++++++GGY+l+++ar++t+ ++
  gene=LOC118517556 288 NV----PTLVVGGGGYTLRNVARCWTYETS 313
                        *8....89******************9987 PP

>> gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036052278.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   -4.1   3.8       2.6   1.3e+04      12      86 ..      47     122 ..      37     142 .. 0.55
   2 ?   -4.4   1.0       3.3   1.6e+04     110     123 ..     538     551 ..     473     562 .. 0.54
   3 !  278.6   0.0   2.3e-86   1.1e-82       1     307 []     717    1030 ..     717    1030 .. 0.90

  Alignments for each domain:
  == domain 1  score: -4.1 bits;  conditional E-value: 2.6
                        HHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC...CCSSSCHCTSTC CS
      Hist_deacetyl  12 lealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses...kedddtylspgs 86
                        + +l+++++l ++     ++ + +++el+  H+++  ++ +el ++  ++e+a++ e +++e    ke+++++++ +s
  gene=LOC118510450  47 ILELQKEQELEKQKL--WHAFQEKNKELEMQHRQQLEHKFQELRDQRIAEEAAQQRERREREAikrKEKHECCANASS 122
                        455566555544322..4455556778888887766666665555555555444444433333443244555555544 PP

  == domain 2  score: -4.4 bits;  conditional E-value: 3.3
                        SEEEETTSS--TT- CS
      Hist_deacetyl 110 rsafalvrPpgHHA 123
                         +  +l +P +HHA
  gene=LOC118510450 538 IQLSVLEDPYTHHA 551
                        22233335555555 PP

  == domain 3  score: 278.6 bits;  conditional E-value: 2.3e-86
                         SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC.......CCSSSCHCT CS
      Hist_deacetyl    1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses.......kedddtyls 83
                         hpe+  Rl++i+++l  + gl+ + +++++ r+at+eel++vH+e +  l  +++ + +k ++ s  ++    +        + d+t+ +
  gene=LOC118510450  717 HPEHSGRLQSIWARLVGT-GLAIR-CDKLRSRKATQEELQTVHTEGHALLFGTSQLNRQKVDT-SRVSFV---RlacggvgVDLDTTWNE 800
                         9****************8.99866.557*******************9999876655555542.222232...13345554145569999 PP

                         STCCHHHHHHHHHHHHHHHHHHTTSSSEEEETTSS--TT-BSSB-BTTBSS-HHHHHHHHHHH..TTTSS-EEEEE-SSS--HHHHHHCT CS
      Hist_deacetyl   84 pgsleaaklaagavleavdavlegevrsafalvrPpgHHAekdkasGFCllNnvaiaakylqk..kyglkrvaivDfDvHhGnGtqeify 171
                          ++ +aa++aag+v++++ +v++ge r++fa+vrPpgHHAe+d+a+GFC++N +a+aa+ l++   ++++rv+ivD+DvHhGnGtq++fy
  gene=LOC118510450  801 HHTAAAARMAAGCVIDLSYKVARGENRNGFAVVRPPGHHAEADAAMGFCFFNSIALAARLLRHrmPHEMRRVLIVDWDVHHGNGTQQAFY 890
                         *************************************************************774467899******************** PP

                         T-SSEEEEEEEE-.TTTSTTCCGSTT---SGGGTTSEEEEEESST....-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTS..T CS
      Hist_deacetyl  172 sdpsvltlSiHry.eesfyPgtgsleeigegkgkgktvnvplekg....ttdeeylkafeeillpaleefkPelivvsaGfDalkgD..p 254
                         +d+svl+lS+Hr+ +++f+Pgtg   e+g g+g g++vnv ++ g    ++d+eyl+af+++++p++++f P++++vsaGfDa+ g   p
  gene=LOC118510450  891 DDASVLYLSVHRHdDGNFFPGTGGPAECGVGAGLGYNVNVAWSGGvnppLGDAEYLAAFRTVVMPIARDFAPDIVLVSAGFDAAVGHpaP 980
                         *************88***************************99766669************************************9999 PP

                         TTSBBB-HHHHHHHHHHHHHHCGS..C-EEEEEECESSHHHHHHHHHHHHHHH CS
      Hist_deacetyl  255 lgelnltaegyaeitkkllelaekvskrlvllleGGYnlealarsvtavlaal 307
                         lg++ ++ + + ++t++l++la+   +++vl leGGY+l a+ +s++++++al
  gene=LOC118510450  981 LGGYVVSPACFGYLTRELMQLAN---GKIVLALEGGYDLPAICDSAEECVRAL 1030
                         **********************8...69****************999998875 PP

>> gene=LOC118510456  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036052268.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   -4.1   3.8       2.7   1.3e+04      12      86 ..      40     115 ..      30     135 .. 0.55
   2 !  278.5   0.0   2.4e-86   1.2e-82       1     307 []     758    1071 ..     758    1071 .. 0.90

  Alignments for each domain:
  == domain 1  score: -4.1 bits;  conditional E-value: 2.7
                        HHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC...CCSSSCHCTSTC CS
      Hist_deacetyl  12 lealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses...kedddtylspgs 86
                        + +l+++++l ++     ++ + +++el+  H+++  ++ +el ++  ++e+a++ e +++e    ke+++++++ +s
  gene=LOC118510456  40 ILELQKEQELEKQKL--WHAFQEKNKELEMQHRQQLEHKFQELRDQRIAEEAAQQRERREREAikrKEKHECCANASS 115
                        445566555544322..4455556778888887766666665555555555444444433333443244555555544 PP

  == domain 2  score: 278.5 bits;  conditional E-value: 2.4e-86
                         SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC.......CCSSSCHCT CS
      Hist_deacetyl    1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses.......kedddtyls 83
                         hpe+  Rl++i+++l  + gl+ + +++++ r+at+eel++vH+e +  l  +++ + +k ++ s  ++    +        + d+t+ +
  gene=LOC118510456  758 HPEHSGRLQSIWARLVGT-GLAIR-CDKLRSRKATQEELQTVHTEGHALLFGTSQLNRQKVDT-SRVSFV---RlacggvgVDLDTTWNE 841
                         9****************8.99866.557*******************9999876655555542.222232...13345554145569999 PP

                         STCCHHHHHHHHHHHHHHHHHHTTSSSEEEETTSS--TT-BSSB-BTTBSS-HHHHHHHHHHH..TTTSS-EEEEE-SSS--HHHHHHCT CS
      Hist_deacetyl   84 pgsleaaklaagavleavdavlegevrsafalvrPpgHHAekdkasGFCllNnvaiaakylqk..kyglkrvaivDfDvHhGnGtqeify 171
                          ++ +aa++aag+v++++ +v++ge r++fa+vrPpgHHAe+d+a+GFC++N +a+aa+ l++   ++++rv+ivD+DvHhGnGtq++fy
  gene=LOC118510456  842 HHTAAAARMAAGCVIDLSYKVARGENRNGFAVVRPPGHHAEADAAMGFCFFNSIALAARLLRHrmPHEMRRVLIVDWDVHHGNGTQQAFY 931
                         *************************************************************774467899******************** PP

                         T-SSEEEEEEEE-.TTTSTTCCGSTT---SGGGTTSEEEEEESST....-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTS..T CS
      Hist_deacetyl  172 sdpsvltlSiHry.eesfyPgtgsleeigegkgkgktvnvplekg....ttdeeylkafeeillpaleefkPelivvsaGfDalkgD..p 254
                         +d+svl+lS+Hr+ +++f+Pgtg   e+g g+g g++vnv ++ g    ++d+eyl+af+++++p++++f P++++vsaGfDa+ g   p
  gene=LOC118510456  932 DDASVLYLSVHRHdDGNFFPGTGGPAECGVGAGLGYNVNVAWSGGvnppLGDAEYLAAFRTVVMPIARDFAPDIVLVSAGFDAAVGHpaP 1021
                         *************88***************************99766669************************************9999 PP

                         TTSBBB-HHHHHHHHHHHHHHCGS..C-EEEEEECESSHHHHHHHHHHHHHHH CS
      Hist_deacetyl  255 lgelnltaegyaeitkkllelaekvskrlvllleGGYnlealarsvtavlaal 307
                         lg++ ++ + + ++t++l++la+   +++vl leGGY+l a+ +s++++++al
  gene=LOC118510456 1022 LGGYVVSPACFGYLTRELMQLAN---GKIVLALEGGYDLPAICDSAEECVRAL 1071
                         **********************8...69****************999998875 PP

>> gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036052258.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   -4.1   3.8       2.7   1.3e+04      12      86 ..      47     122 ..      37     142 .. 0.55
   2 !  278.5   0.0   2.4e-86   1.2e-82       1     307 []     765    1078 ..     765    1078 .. 0.90

  Alignments for each domain:
  == domain 1  score: -4.1 bits;  conditional E-value: 2.7
                        HHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC...CCSSSCHCTSTC CS
      Hist_deacetyl  12 lealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses...kedddtylspgs 86
                        + +l+++++l ++     ++ + +++el+  H+++  ++ +el ++  ++e+a++ e +++e    ke+++++++ +s
  gene=LOC118510450  47 ILELQKEQELEKQKL--WHAFQEKNKELEMQHRQQLEHKFQELRDQRIAEEAAQQRERREREAikrKEKHECCANASS 122
                        445566555544322..4455556778888887766666665555555555444444433333443244555555544 PP

  == domain 2  score: 278.5 bits;  conditional E-value: 2.4e-86
                         SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCC.......CCSSSCHCT CS
      Hist_deacetyl    1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskses.......kedddtyls 83
                         hpe+  Rl++i+++l  + gl+ + +++++ r+at+eel++vH+e +  l  +++ + +k ++ s  ++    +        + d+t+ +
  gene=LOC118510450  765 HPEHSGRLQSIWARLVGT-GLAIR-CDKLRSRKATQEELQTVHTEGHALLFGTSQLNRQKVDT-SRVSFV---RlacggvgVDLDTTWNE 848
                         9****************8.99866.557*******************9999876655555542.222232...13345554145569999 PP

                         STCCHHHHHHHHHHHHHHHHHHTTSSSEEEETTSS--TT-BSSB-BTTBSS-HHHHHHHHHHH..TTTSS-EEEEE-SSS--HHHHHHCT CS
      Hist_deacetyl   84 pgsleaaklaagavleavdavlegevrsafalvrPpgHHAekdkasGFCllNnvaiaakylqk..kyglkrvaivDfDvHhGnGtqeify 171
                          ++ +aa++aag+v++++ +v++ge r++fa+vrPpgHHAe+d+a+GFC++N +a+aa+ l++   ++++rv+ivD+DvHhGnGtq++fy
  gene=LOC118510450  849 HHTAAAARMAAGCVIDLSYKVARGENRNGFAVVRPPGHHAEADAAMGFCFFNSIALAARLLRHrmPHEMRRVLIVDWDVHHGNGTQQAFY 938
                         *************************************************************774467899******************** PP

                         T-SSEEEEEEEE-.TTTSTTCCGSTT---SGGGTTSEEEEEESST....-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTS..T CS
      Hist_deacetyl  172 sdpsvltlSiHry.eesfyPgtgsleeigegkgkgktvnvplekg....ttdeeylkafeeillpaleefkPelivvsaGfDalkgD..p 254
                         +d+svl+lS+Hr+ +++f+Pgtg   e+g g+g g++vnv ++ g    ++d+eyl+af+++++p++++f P++++vsaGfDa+ g   p
  gene=LOC118510450  939 DDASVLYLSVHRHdDGNFFPGTGGPAECGVGAGLGYNVNVAWSGGvnppLGDAEYLAAFRTVVMPIARDFAPDIVLVSAGFDAAVGHpaP 1028
                         *************88***************************99766669************************************9999 PP

                         TTSBBB-HHHHHHHHHHHHHHCGS..C-EEEEEECESSHHHHHHHHHHHHHHH CS
      Hist_deacetyl  255 lgelnltaegyaeitkkllelaekvskrlvllleGGYnlealarsvtavlaal 307
                         lg++ ++ + + ++t++l++la+   +++vl leGGY+l a+ +s++++++al
  gene=LOC118510450 1029 LGGYVVSPACFGYLTRELMQLAN---GKIVLALEGGYDLPAICDSAEECVRAL 1078
                         **********************8...69****************999998875 PP

>> gene=LOC118505081  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036040376.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  184.2   0.0   1.2e-57   5.9e-54       1     303 [.      63     347 ..      63     350 .. 0.91

  Alignments for each domain:
  == domain 1  score: 184.2 bits;  conditional E-value: 1.2e-57
                        SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCCCCSSSCHCTSTCCHHHHH CS
      Hist_deacetyl   1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskseskedddtylspgsleaakl 92
                        hp+++++  +i++ l+++ gl+++ e++++p e+t eell+vH+++Y+++l+ + + +k  e+ ++l +         ++++ ++ l+ ++
  gene=LOC118505081  63 HPFDAAKGGNIYRLLKTN-GLIRNDEDVYAPDEITPEELLEVHTKRYMDSLKWSLNVAKIAEIPPLLFV--------PNCFVQRSYLRPMRF 145
                        677777888787777776.*****9***************************99998888886666544........46************* PP

                        HHHHHHHHHHHHHTTSSSEEEETT.SS--TT-BSSB-BTTBSS-HHHHHHHHHHH.TTTSS-EEEEE-SSS--HHHHHHCTT-SSEEEEEEE CS
      Hist_deacetyl  93 aagavleavdavlegevrsafalv.rPpgHHAekdkasGFCllNnvaiaakylqk.kyglkrvaivDfDvHhGnGtqeifysdpsvltlSiH 182
                        ++ +++ a++a+l++    ++a++  +++HH+ +d+  GFC + ++ +++k lq    g++r++ivD+D+H+GnG ++ + +d+ v++l+++
  gene=LOC118505081 146 QTSGSMLAARAALQS--GLGWAINlGGGFHHCSADRGGGFCPYADITLTVKMLQTsGNGIDRILIVDLDAHQGNGYERDLMHDAGVFILDMY 235
                        *************88..999999999***************************883455********************************* PP

                        E-TTTSTTCCGSTT---SGGGTTSEEEEEESST-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTSTTTSBBB-HHHHHHHHHHHHH CS
      Hist_deacetyl 183 ryeesfyPgtgsleeigegkgkgktvnvplekgttdeeylkafeeillpaleefkPelivvsaGfDalkgDplgelnltaegyaeitkklle 274
                        +y   +yP  ++++ +           v+l+++t+d+eyl+ ++++l + l+ef+P++i+++aG+D lkgDplg l++t eg+ e  +++ +
  gene=LOC118505081 236 NY--RIYPRDHTAKLA-------IRRAVELKPHTDDAEYLRKLRNCLQRSLAEFEPNFIIYNAGTDILKGDPLGLLDITPEGVIERDEFVFR 318
                        *7..56**77777666.......77899**************************************************************** PP

                        HCGS..C-EEEEEECESSHHHHHHHHHHH CS
      Hist_deacetyl 275 laekvskrlvllleGGYnlealarsvtav 303
                         a++ s ++v+ll GGY  ++ +  + ++
  gene=LOC118505081 319 CAQERSIPVVMLLSGGYLRSSARVIASSI 347
                        ****999**********998877666655 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (307 nodes)

# 4) EEF1AKMT4

In [22]:
!grep PF08241 Pfam-A.hmm

ACC   PF08241.15

In [23]:
!hmmfetch Pfam-A.hmm.h3m PF08241.15 > EEF1AKMT4.hmm
!hmmstat EEF1AKMT4.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      Methyltransf_11      PF08241.15        141     7.11     96   0.60   0.61   0.48   0.01

In [24]:
!hmmsearch EEF1AKMT4.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  EEF1AKMT4.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Methyltransf_11  [M=96]
Accession:   PF08241.15
Description: Methyltransferase domain
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence               Description
    ------- ------ -----    ------- ------ -----   ---- --  --------               -----------
    1.7e-20   74.1   0.0    2.8e-20   73.5   0.0    1.3  1  gene=LOC118506044       scaffold=NC_050202.1 strand=+ Parent=
    1.1e-18   68.3   0.0    1.9e-18   67.6   0.0    1.4  1  gene=LOC118516408       scaffold=NW_023405224.1 strand=+ Pare
    4.2e-18   66.5   0.0      9e-18   65.4   0.0    1.6  1  gene=LOC118504071       scaffold=NC_050202.1 strand=+ Parent=
    1.9e-17   64.4   0.2    6.2e-17   62.7   0.2    1.9  1  gene=LOC118508064       scaffold=NC_050202.1 strand=+ Parent=
    2.7e-15   57.5   0.0    6.4e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.5e-15   56.3   0.0    1.7  1  gene=LOC118506400       scaffold=NC_050202.1 strand=+ Parent=
    2.8e-15   57.4   0.0    6.4e-15   56.3   0.0    1.7  1  gene=LOC118506399       scaffold=NC_050202.1 strand=+ Parent=
    1.1e-13   52.3   0.1    4.1e-13   50.5   0.0    1.9  2  gene=LOC118513415       scaffold=NC_050203.1 strand=+ Parent=
    1.1e-13   52.3   0.1    4.1e-13   50.5   0.0    1.9  2  gene=LOC118513416       scaffold=NC_050203.1 strand=+ Parent=
    1.8e-13   51.6   0.1    1.4e-12   48.8   0.0    2.5  2  gene=LOC118514289       scaffold=NC_050203.1 strand=+ Parent=
      8e-12   46.4   0.0    1.5e-11   45.5   0.0    1.5  1  gene=LOC118513053       scaffold=NC_050203.1 strand=+ Parent=
    5.8e-10   40.4   0.0    2.8e-09   38.2   0.0    2.0  1  gene=LOC118502774       scaffold=NC_050202.1 strand=- Parent=
    7.8e-10   40.0   0.0    1.3e-09   39.3   0.0    1.3  1  gene=LOC118512749       scaffold=NC_050203.1 strand=+ Parent=
    1.2e-09   39.4   0.1    1.1e-08   36.3   0.0    2.6  2  gene=LOC118514287       scaffold=NC_050203.1 strand=+ Parent=
    4.2e-07   31.2   0.0    2.1e-06   29.0   0.0    2.2  1  gene=LOC118504700       scaffold=NC_050202.1 strand=+ Parent=
    4.8e-07   31.0   0.0    1.7e-06   29.3   0.0    1.9  1  gene=LOC118508587       scaffold=NC_050202.1 strand=- Parent=
      1e-06   30.0   0.0    2.7e-06   28.6   0.0    1.7  1  gene=LOC118508016       scaffold=NC_050202.1 strand=- Parent=
    6.1e-06   27.5   0.5      3e-05   25.3   0.2    2.3  1  gene=LOC118514067       scaffold=NC_050203.1 strand=- Parent=
      1e-05   26.8   0.0    2.9e-05   25.3   0.0    1.8  1  gene=LOC118502676       scaffold=NC_050202.1 strand=+ Parent=
      1e-05   26.8   0.0    2.9e-05   25.3   0.0    1.8  1  gene=LOC118502704       scaffold=NC_050202.1 strand=+ Parent=
    0.00016   22.9   0.0    0.00046   21.5   0.0    1.8  1  gene=LOC118508994       scaffold=NC_050203.1 strand=- Parent=
    0.00045   21.5   0.1      0.019   16.3   0.0    2.4  2  gene=LOC118510753       scaffold=NC_050203.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517473       scaffold=NC_050201.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0012   20.1   0.0     0.0058   17.9   0.0    2.1  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0019   19.5   0.0     0.0075   17.6   0.0    2.0  1  gene=LOC118517474       scaffold=NC_050201.1 strand=+ Parent=
     0.0044   18.3   0.0      0.012   16.9   0.0    1.7  1  gene=LOC118507371       scaffold=NC_050202.1 strand=- Parent=
     0.0065   17.8   0.0      0.032   15.6   0.0    2.2  1  gene=LOC118504836       scaffold=NC_050202.1 strand=+ Parent=
  ------ inclusion threshold ------
      0.012   16.9   0.1        0.2   13.1   0.0    2.6  1  gene=LOC118512384       scaffold=NC_050203.1 strand=+ Parent=
      0.012   16.9   0.1        0.2   13.1   0.0    2.6  1  gene=LOC118512389       scaffold=NC_050203.1 strand=+ Parent=
      0.012   16.9   0.1        0.2   13.1   0.0    2.6  1  gene=LOC118512389       scaffold=NC_050203.1 strand=+ Parent=
      0.012   16.9   0.1        0.2   13.1   0.0    2.6  1  gene=LOC118512389       scaffold=NC_050203.1 strand=+ Parent=
      0.031   15.6   0.0      0.085   14.2   0.0    1.8  1  exception=unclassified  translation discrepancy scaffold=NC_0
      0.035   15.5   0.0      0.077   14.4   0.0    1.6  1  exception=unclassified  translation discrepancy scaffold=NC_0
       0.16   13.3   0.0       0.35   12.3   0.0    1.7  1  gene=LOC118508889       scaffold=NC_050203.1 strand=+ Parent=
       0.25   12.7   0.0       0.61   11.5   0.0    1.7  1  gene=LOC118514218       scaffold=NC_050203.1 strand=- Parent=
       0.26   12.7   0.2        5.9    8.3   0.1    2.6  2  gene=LOC118511629       scaffold=NC_050203.1 strand=+ Parent=


Domain annotation for each sequence (and alignments):
>> gene=LOC118506044  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036042673.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   73.5   0.0   4.3e-23   2.8e-20       1      96 []     100     200 ..     100     200 .. 0.95

  Alignments for each domain:
  == domain 1  score: 73.5 bits;  conditional E-value: 4.3e-23
                        EEET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-....EEEETTEECCCT.SS-TT-EEEEEEES-CCC-CCHHHHHHHHHHH CS
    Methyltransf_11   1 LdvGcGtGrlaealakrgarvvgvDlskemlklakekaseegl....kvefvvadaekl.pfednsfDlvvssevlhhvedpekalkeiaRv 87
                        L+vGcG+G+l+ealak  ++vvg+D+s++++++ak++a++++     +++++v+++e+    + + +D+vv+sevl+hv+d  ++++++
  gene=LOC118506044 100 LEVGCGGGILTEALAKLNSKVVGIDPSEKLINVAKQHAKDDKSldpeQIQYHVETIEQHaAKNAERYDAVVASEVLEHVNDKVAFIEQCLAA 191
                        89**************************************9999*************98345558*************************** PP

                        EEEEEEEEE CS
    Methyltransf_11  88 LkpgGllvi 96
                        LkpgG ++i
  gene=LOC118506044 192 LKPGGSMFI 200
                        *****9876 PP

>> gene=LOC118516408  scaffold=NW_023405224.1 strand=+ Parent=rna-XM_036062272.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   67.6   0.0   2.9e-21   1.9e-18       1      96 []     113     212 ..     113     212 .. 0.96

  Alignments for each domain:
  == domain 1  score: 67.6 bits;  conditional E-value: 2.9e-21
                        EEET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-...EEEETTEECCCT.SS-TT-EEEEEEES-CCC-CCHHHHHHHHHHHE CS
    Methyltransf_11   1 LdvGcGtGrlaealakrgarvvgvDlskemlklakekaseegl...kvefvvadaekl.pfednsfDlvvssevlhhvedpekalkeiaRvL 88
                        LdvGcG+G+++ealak  a+vvg+D++  ++++ak++a++++    ++++ ++++ +  + + +++D+vv+se+++h+ d++ +lk++a vL
  gene=LOC118516408 113 LDVGCGGGIYTEALAKLHATVVGIDPARHLIEVAKAHAEKQPDikeRCQYYEQSLDDHwQGAVGKYDVVVLSETIEHMVDQSTLLKQVAAVL 204
                        8***************************************999999999999999996689999**************************** PP

                        EEEEEEEE CS
    Methyltransf_11  89 kpgGllvi 96
                        kpgG ++i
  gene=LOC118516408 205 KPGGSVFI 212
                        ****9986 PP

>> gene=LOC118504071  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036038185.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   65.4   0.0   1.4e-20     9e-18       1      95 [.      79     171 ..      79     172 .. 0.91

  Alignments for each domain:
  == domain 1  score: 65.4 bits;  conditional E-value: 1.4e-20
                        EEET-TTSHHHHHHH.HTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-CCHHHHHHHHHHHEEEE CS
    Methyltransf_11   1 LdvGcGtGrlaeala.krgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhvedpekalkeiaRvLkpg 91
                        +d+G+G+G++++++  +++ ++++vDls++ml +    +  +gl ++++++d e+++fed+s Dlvvss ++h+++d+ ++++ + R Lkp+
  gene=LOC118504071  79 VDLGAGRGYVTNHVLgETVQKLTAVDLSPAMLSQI---KGSPGLDFSIREMDEERFQFEDDSLDLVVSSLSMHWINDLPACFRAVNRALKPD 167
                        59*************7777*************544...4555556899******************************************** PP

                        EEEE CS
    Methyltransf_11  92 Gllv 95
                        G+++
  gene=LOC118504071 168 GVFI 171
                        *997 PP

>> gene=LOC118508064  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036047522.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   62.7   0.2   9.6e-20   6.2e-17       1      95 [.     397     486 ..     397     487 .. 0.93

  Alignments for each domain:
  == domain 1  score: 62.7 bits;  conditional E-value: 9.6e-20
                        EEET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEE CS
    Methyltransf_11   1 LdvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLk 89
                        LdvGcG+G++++  +  +a  +g+D s+ +l+++ +++       +++++d+  +pf+d+s+D+++s  v+hh+   +++++a++e++RvL+
  gene=LOC118508064 397 LDVGCGNGKYLASSE--CALMLGCDRSEGLLQVCVDRGF------NVLQCDCLAVPFRDESVDACISIAVIHHLatdQRRKQAISEMVRVLR 480
                        8**********9999..999***********99955554......469**************************9999************** PP

                        EEEEEE CS
    Methyltransf_11  90 pgGllv 95
                        pgG+ +
  gene=LOC118508064 481 PGGKAL 486
                        ***976 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043460.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0   9.9e-18   6.4e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 9.9e-18
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043454.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043458.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043456.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043451.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043452.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173
                        9*************555.9**************99999987.....777777.9*******************9999*************** PP

                        EEEEEE CS
    Methyltransf_11  91 gGllvi 96
                        gG+++i
  gene=LOC118506399 174 GGRVII 179
                        ***986 PP

>> gene=LOC118506399  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036043455.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   56.3   0.0     1e-17   6.5e-15       2      96 .]      89     179 ..      88     179 .. 0.93

  Alignments for each domain:
  == domain 1  score: 56.3 bits;  conditional E-value: 1e-17
                        EET-TTSHHHHHHHHTTSEEEEEES-HHHHHHHHHHCCHHT-EEEETTEECCCTSS-TT-EEEEEEES-CCC-...CCHHHHHHHHHHHEEE CS
    Methyltransf_11   2 dvGcGtGrlaealakrgarvvgvDlskemlklakekaseeglkvefvvadaeklpfednsfDlvvssevlhhv...edpekalkeiaRvLkp 90
                        dvGcG+Gr++  +      ++gvD + +++++a+ k+ e       ++ ++e lpf+d+sfD+v+s  v+hh+   e++  a++e+aR+L+
  gene=LOC118506399  89 DVGCGNGRYLSGFNPLI-YTIGVDRCYRLTQVAHGKGGEVA-----ICDNLE-LPFRDESFDAVLSLAVVHHFattERRVGAIRELARILRI 173

# 5) SUDS3

In [25]:
!grep PF08598 Pfam-A.hmm

ACC   PF08598.14

In [26]:
!hmmfetch Pfam-A.hmm.h3m PF08598.14 > SUDS3.hmm
!hmmstat SUDS3.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      Sds3                 PF08598.14         59     4.57    218   0.59   0.59   0.43   0.07

In [27]:
!hmmsearch SUDS3.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  SUDS3.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Sds3  [M=218]
Accession:   PF08598.14
Description: Sds3-like
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    1.2e-18   68.7   6.5    4.5e-18   66.8   6.5    1.7  1  gene=LOC118505026  scaffold=NC_050202.1 strand=+ Parent=rna-X
    4.8e-17   63.4   1.7    6.9e-17   62.9   1.7    1.3  1  gene=LOC118517433  scaffold=NC_050201.1 strand=+ Parent=rna-X
    4.8e-17   63.4   1.7    6.9e-17   62.9   1.7    1.3  1  gene=LOC118517441  scaffold=NC_050201.1 strand=+ Parent=rna-X
      7e-06   26.9   8.1    1.2e-05   26.2   8.0    1.5  1  gene=LOC118509611  scaffold=NC_050203.1 strand=- Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118505026  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036040236.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   66.8   6.5   6.1e-22   4.5e-18       2     132 ..      63     194 ..      62     225 .. 0.90

  Alignments for each domain:
  == domain 1  score: 66.8 bits;  conditional E-value: 6.1e-22
               Sds3   2 lekltkiessFaedRDklYrerLtaLqteltllqqGthpellrklrdleeerDaeLkrlrlreeyqlkriekefkadiekakqeheklvkll 93
                        ++ lt++e++F  ++++lY+er+ ++ ++l+++  G  +++   l++l++++D + + ++ +++y++++i+++f+ ++++  q+++++ +l+
  gene=LOC118505026  63 QDNLTSLEKQFGILKEQLYKERMVQVDYKLQQIRGGRLQDYFIPLQQLQTNMDSRKEVAEVMKKYRVNNIKNKFESELQACYQHFDSEQNLA 154
                        789***************************************************************************************** PP

               Sds3  94 keklyeeiekkikrLkeeklqlDlanansl....kktrshta.g 132
                         + + +e+ +k +rL+e++ ++D+    s+    ++tr++++ g
  gene=LOC118505026 155 NDVICDELMEKVRRLEEDRHNVDI----SWadwgTNTRTAKVrG 194
                        ************************....5655567777776652 PP

>> gene=LOC118517433  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063555.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   62.9   1.7   9.3e-21   6.9e-17      14     124 ..      59     193 ..      58     309 .. 0.77

  Alignments for each domain:
  == domain 1  score: 62.9 bits;  conditional E-value: 9.3e-21
               Sds3  14 edRDklYrerLtaLqteltllqqGthpellrklrdleeerDaeLkrlrlreeyqlkriekefkadiekakqeheklvkllkeklyeeiekki 105
                        e ++++Y+++L++L  +l+l++q + pe+l+ +++l++e D++L + +  ++y l ++e+    +  +a++e+e+++++l e+l++++e ++
  gene=LOC118517433  59 EIKEQMYQDKLANLLGQLELCKQRKQPEYLKIVERLQNELDDRLLLNEVERDYLLACAERDCILEKAAAEKEYEEKKAELIENLIADLEDQK 150
                        5799**************************************************************************************** PP

               Sds3 106 krLkeeklqlDlanansl.........................k 124
                        k +++e   ++l n  sl                         k
  gene=LOC118517433 151 KMIEQEFSSMEL-NGDSLdlkptvtrklrrrpneplpvpekrrK 193
                        ************.9999977555554444444444444322221 PP

>> gene=LOC118517441  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063554.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   62.9   1.7   9.3e-21   6.9e-17      14     124 ..      59     193 ..      58     309 .. 0.77

  Alignments for each domain:
  == domain 1  score: 62.9 bits;  conditional E-value: 9.3e-21
               Sds3  14 edRDklYrerLtaLqteltllqqGthpellrklrdleeerDaeLkrlrlreeyqlkriekefkadiekakqeheklvkllkeklyeeiekki 105
                        e ++++Y+++L++L  +l+l++q + pe+l+ +++l++e D++L + +  ++y l ++e+    +  +a++e+e+++++l e+l++++e ++
  gene=LOC118517441  59 EIKEQMYQDKLANLLGQLELCKQRKQPEYLKIVERLQNELDDRLLLNEVERDYLLACAERDCILEKAAAEKEYEEKKAELIENLIADLEDQK 150
                        5799**************************************************************************************** PP

               Sds3 106 krLkeeklqlDlanansl.........................k 124
                        k +++e   ++l n  sl                         k
  gene=LOC118517441 151 KMIEQEFSSMEL-NGDSLdlkptvtrklrrrpneplpvpekrrK 193
                        ************.9999977555554444444444444322221 PP

>> gene=LOC118509611  scaffold=NC_050203.1 strand=- Parent=rna-XM_036050418.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   26.2   8.0   1.6e-09   1.2e-05      17     115 ..      42     140 ..      39     201 .. 0.89

  Alignments for each domain:
  == domain 1  score: 26.2 bits;  conditional E-value: 1.6e-09
               Sds3  17 DklYrerLtaLqteltllqqGthpellrklrdleeerDaeLkrlrlreeyqlkriekefkadiekakqeheklvkllkeklyeeiekkikrL 108
                        ++lYr++ ++L  +l+l +q +hp +l+ +++l++e  ++ ++ +  ++  l ++ +    +i +a+qe+ +++++l  + ++++e+++k L
  gene=LOC118509611  42 EQLYRKQRADLLGQLELAKQRKHPAYLKIVQRLQTELSDRVALNEIERDAALASAHQDCLREIAAAEQEFAEKKAELIANAIADLEQEKKTL 133
                        689***************************************************************************************** PP

               Sds3 109 keeklql 115
                         +e   +
  gene=LOC118509611 134 RQEIDAM 140
                        9996555 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (218 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      2753  (0.0928186); expected 593.2 (0.02)
Passed bias filter:                      609  (0.0205327); expected 593.2 (0.02)
Passed Vit filter:                       108  (0.00364127); expected 29.7 (0.001)
Passed Fwd filter:                         4  (0.000134862); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               4  [number of targets reported over threshold]
# CPU time: 0.69u 0.02s 00:00:00.71 Elapsed: 00:00:00.68
# Mc/sec: 4212.77
//
[ok]

# 6) SIRT2

In [28]:
!grep PF02146 Pfam-A.hmm

ACC   PF02146.20

In [29]:
!hmmfetch Pfam-A.hmm.h3m PF02146.20 > SIRT2.hmm
!hmmstat SIRT2.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      SIR2                 PF02146.20         18     1.22    179   0.59   0.56   0.51   0.01

In [30]:
!hmmsearch SIRT2.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  SIRT2.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       SIR2  [M=179]
Accession:   PF02146.20
Description: Sir2 family
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    1.3e-57  195.4   0.0    2.5e-57  194.4   0.0    1.5  1  gene=LOC118504478  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.4e-45  156.1   0.0    2.4e-45  155.4   0.0    1.4  1  gene=LOC118502642  scaffold=NC_050202.1 strand=- Parent=rna-X
    1.6e-24   87.5   0.1    1.7e-17   64.7   0.0    3.5  3  gene=LOC118507949  scaffold=NC_050202.1 strand=+ Parent=rna-X
  ------ inclusion threshold ------
      0.035   14.8   1.5      0.035   14.8   1.5    3.4  4  gene=LOC118504644  scaffold=NC_050202.1 strand=+ Parent=rna-X
        1.4    9.6  21.1        7.6    7.1   4.6    3.9  4  gene=LOC118509020  scaffold=NC_050203.1 strand=- Parent=rna-X
        1.8    9.2   8.0       0.52   10.9   3.8    1.9  2  gene=LOC118515208  scaffold=NW_023405006.1 strand=+ Parent=rn


Domain annotation for each sequence (and alignments):
>> gene=LOC118504478  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036038988.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  194.4   0.0   5.1e-61   2.5e-57       1     179 []     180     361 ..     180     361 .. 0.99

  Alignments for each domain:
  == domain 1  score: 194.4 bits;  conditional E-value: 5.1e-61
                        -GGGGGGGT---SST.TTSHHHHSCHHHHSSHHHHHHHHHHHHHTHHHHHHHHHHHCCTSS--HHHHHHHHHHHTTCEEEEEES-SSSHHHH CS
               SIR2   1 GAGiStesGipdfRs.keGlyaklakeelaspeavfskkllkeePevfyniarellaeeaepnelHkalkklekkgkllrliTQNiDgLekk 91
                        GAGiSt++GipdfRs ++Gly++l k++l  p+a+f+ ++l ++P++f ++a+el++ +++p+++H++++ le+kg l+r +TQNiD+Le+
  gene=LOC118504478 180 GAGISTSAGIPDFRSpDTGLYNNLMKYNLPYPQAIFELEYLYQNPKPFFTLAKELYPGTFKPTPSHYFVRLLEQKGLLVRHYTQNIDTLERI 271
                        9******************************************************************************************* PP

                        TT-S..SEEETTEEEEEEEETTTSBEEECCGGHCHHHTTTC.BSTTTCCBEEEEE--CTSB-SHHHHHHHH.HHHH-SEEEEES--STSTT CS
               SIR2  92 aGsk..kvvelHGslakvkCvkcekkltaeelqeeieaekvpecekcggllkpdvvfFGealpdklkklle.kveeadlliviGtSlkVap 179
                        aG++  k+ve+HG++ + +C +c++ ++ e ++e i + +vp+c+ cgg++kpd+vfFGe lp++++ l + +  e+dlli++GtSl+V+p
  gene=LOC118504478 272 AGISeeKIVEAHGTFYTNHCLQCKTAYSLEFVKEIIFTDEVPTCP-CGGVIKPDIVFFGEGLPERFHMLPHqDFAECDLLIIMGTSLTVQP 361
                        ***999************************************997.***********************999*****************98 PP

>> gene=LOC118502642  scaffold=NC_050202.1 strand=- Parent=rna-XM_036035085.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  155.4   0.0   4.9e-49   2.4e-45       1     178 [.      53     265 ..      53     266 .. 0.92

  Alignments for each domain:
  == domain 1  score: 155.4 bits;  conditional E-value: 4.9e-49
                        -GGGGGGGT---SST.TTSHHHHSCHHHHSSHHHHHHHHHHHHHTHHHHHHHHHHHCC.TSS--HHHHHHHHHHHTTCEEEEEES-SSSHHH CS
               SIR2   1 GAGiStesGipdfRs.keGlyaklakeelaspeavfskkllkeePevfyniarellae.eaepnelHkalkklekkgkllrliTQNiDgLek 90
                        GAGiStesGipd+Rs   Glya+ +++++++ + v+s+ ++k++   + +++  ++++ +++pn +H+ l+ le++g+ + ++TQN+D L+
  gene=LOC118502642  53 GAGISTESGIPDYRSeGVGLYARSNHKPIQHGDFVKSEATRKRY---WARNYVGWPRFsSIAPNVTHYTLARLEREGRISGIVTQNVDRLHG 141
                        9**************889**************************...***********99******************************** PP

                        HTT-SSEEETTEEEEEEEETTTSBEEECCGGHCHHHTTTC.....................................BSTTTCCBEEEEE-- CS
               SIR2  91 kaGskkvvelHGslakvkCvkcekkltaeelqeeieaekvp....................................ecekcggllkpdvvf 146
                        kaGsk+vvelHGs   v Cv  +  ++++ ++ +ie+++ +                                     c++cgg lkp++vf
  gene=LOC118502642 142 KAGSKEVVELHGSGYDVICVGNQD-ERGKGCNYRIERHEFQhildqlnpamedkstmmrpdgdvelsmeyvegfkipPCPQCGGNLKPEIVF 232
                        *******************96444.4444455555554444555666667****************************************** PP

                        CTSB-S.HHHHHHHHHHHH-SEEEEES--STST CS
               SIR2 147 FGealp.dklkkllekveeadlliviGtSlkVa 178
                        FG+++p  +++k+++ + e d ++v+G+Sl+V
  gene=LOC118502642 233 FGDNVPmPRIEKVVRMIIESDGVLVLGSSLTVF 265
                        *******************************96 PP

>> gene=LOC118507949  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036047254.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   18.2   0.0   6.4e-07    0.0032       1      25 [.     115     139 ..     115     148 .. 0.91
   2 !   64.7   0.0   3.4e-21   1.7e-17      59     178 ..     151     282 ..     143     283 .. 0.85
   3 ?   -0.4   0.0      0.32   1.6e+03     117     145 ..     564     592 ..     555     600 .. 0.87

  Alignments for each domain:
  == domain 1  score: 18.2 bits;  conditional E-value: 6.4e-07
                        -GGGGGGGT---SSTTTSHHHHSCH CS
               SIR2   1 GAGiStesGipdfRskeGlyaklak 25
                        GAGiSt++ ipd+R+++G+++ l++
  gene=LOC118507949 115 GAGISTSAKIPDYRGSQGIWTLLEQ 139
                        9*******************97765 PP

  == domain 2  score: 64.7 bits;  conditional E-value: 3.4e-21
                        SS--HHHHHHHHHHHTTCEEEEEES-SSSHHHHTT-S..SEEETTEEEEEEEETTTSBEEECCGGHCHHHTTTC.......BSTTTCCBEEE CS
               SIR2  59 aepnelHkalkklekkgkllrliTQNiDgLekkaGsk..kvvelHGslakvkCvkcekkltaeelqeeieaekvp......ecekcggllkp 142
                        a p+ +H al +l ++g l+ ++ QN DgL+ ++G+    + e+HG++    C +c+ + ++ +l+++++ +         +c++cgg l
  gene=LOC118507949 151 ADPTFTHMALFELHRRGILKHVLSQNCDGLHLRSGLPrfSLSEVHGNMYVEVCKQCKPNAEYWRLFDTTQFTARHyhktnrRCRRCGGPLID 242
                        57999*******************************9899*****************999888877777655444455566*********** PP

                        EE--CTSB-S....HHHHHHHHHHHH-SEEEEES--STST CS
               SIR2 143 dvvfFGealp....dklkkllekveeadlliviGtSlkVa 178
                        ++v FGe  +     ++  ++ ++e++dl+++iG+SlkV
  gene=LOC118507949 243 TIVHFGERGQlkwpLNWAGVTPHTEKTDLILCIGSSLKVL 282
                        *******7552122455666669***************95 PP

  == domain 3  score: -0.4 bits;  conditional E-value: 0.32
                        ECCGGHCHHHTTTC.BSTTTCCBEEEEE- CS
               SIR2 117 taeelqeeieaekvpecekcggllkpdvv 145
                        ++++l + + ++k+p c++++ ++kp vv
  gene=LOC118507949 564 DKSSLLDAAAQKKPPMCNQIQLIVKPVVV 592
                        5667788889999*************998 PP

>> gene=LOC118504644  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036039402.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   -3.5   0.1       2.9   1.4e+04     102     153 ..      67      82 ..      28      98 .. 0.58
   2 ?   -1.4   0.1      0.67   3.3e+03     107     118 ..     209     220 ..     169     236 .. 0.66
   3 ?   14.8   1.5   7.1e-06     0.035      92     150 ..     324     387 ..     317     404 .. 0.76
   4 ?   -0.1   5.0      0.26   1.3e+03     103     137 ..     420     458 ..     387     465 .. 0.76

  Alignments for each domain:
  == domain 1  score: -3.5 bits;  conditional E-value: 2.9
                        EEEEEEEETTTSBEEECCGGHCHHHTTTC.BSTTTCCBEEEEE--CTSB-SH CS
               SIR2 102 GslakvkCvkcekkltaeelqeeieaekvpecekcggllkpdvvfFGealpd 153
                        G+l +  C  c+ ++                                    +
  gene=LOC118504644  67 GTLPTKICFCCKDII------------------------------------T 82
                        444444444444433....................................3 PP

  == domain 2  score: -1.4 bits;  conditional E-value: 0.67
                        EEETTTSBEEEC CS
               SIR2 107 vkCvkcekklta 118
                        ++C +c++ l++
  gene=LOC118504644 209 FHCEQCDNYLDR 220
                        345555555554 PP

  == domain 3  score: 14.8 bits;  conditional E-value: 7.1e-06
                        TT-SSEEETTEEEEEEEETTTSBEEECCGGHCHHHTTTC......BSTTTCCBEEEEE--CTSB CS
               SIR2  92 aGskkvvelHGslakvkCvkcekkltaeelqeeieaekvp.....ecekcggllkpdvvfFGea 150
                        a s +v ++H +++k++C+ cekk+ + +l ++  a+  +      c+ c +  k++v ++  +
  gene=LOC118504644 324 AYSYHVNQVHLNIKKFDCTFCEKKFGNRRLLNNHIANLHSrernfGCTVCDKRFKTNVALYNHM 387
                        55569*******************9887766554433333345559*************99765 PP

  == domain 4  score: -0.1 bits;  conditional E-value: 0.26
                        EEEEEEETTTSBEEECCGGHCHHHTTTC.....BSTTTC CS
               SIR2 103 slakvkCvkcekkltaeelqeeieaekvp....ecekcg 137
                        +  + +C++c+kk++++e+ ++ + ++v+    +c+ cg
  gene=LOC118504644 420 DERNYSCSQCDKKFNTNECLQKHKLTHVTtepyQCPLCG 458
                        456778999999999988887777655554555777776 PP

>> gene=LOC118509020  scaffold=NC_050203.1 strand=- Parent=rna-XM_036049058.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    5.3   1.1    0.0056        28     104     142 ..     265     304 ..     255     311 .. 0.81
   2 ?    7.1   4.6    0.0015       7.6      93     139 ..     307     361 ..     302     388 .. 0.86
   3 ?    5.0   3.4     0.007        35      99     146 ..     374     426 ..     363     446 .. 0.62
   4 ?    6.0   0.8    0.0034        17      93     137 ..     397     445 ..     392     477 .. 0.74

  Alignments for each domain:
  == domain 1  score: 5.3 bits;  conditional E-value: 0.0056
                        EEEEEETTTSBEEEC.CGGHCHHHTTTC.BSTTTCCBEEE CS
               SIR2 104 lakvkCvkcekklta.eelqeeieaekvpecekcggllkp 142
                        + ++kC +c+ ++++  +l+++ ++++  +c+ cg++l
  gene=LOC118509020 265 ARQFKCDQCSFSFHKlYHLKQHKKRHERVRCTICGKVLAG 304
                        6799******9997625677777788899*******9865 PP

  == domain 2  score: 7.1 bits;  conditional E-value: 0.0015
                        T-S.SEEETTEEEEEEEETTTSBEEECCGGHCHHHTTTC........BSTTTCCB CS
               SIR2  93 Gsk.kvvelHGslakvkCvkcekkltaeelqeeieaekvp.......ecekcggl 139
                        G+k ++ ++HG+ +k  C +c+k+++ + + e+  +++ +       +c++c +
  gene=LOC118509020 307 GLKgHMQKMHGNDNKQICPTCGKEFRCNLAMERHLKAHLGtltiervQCDQCDKW 361
                        777799*********************9999999888888899999999999874 PP

  == domain 3  score: 5.0 bits;  conditional E-value: 0.007
                        ETTEEEEEEEETTTSBEEECCGGHCHHHTTTC......BSTTTCCBEEEEE-- CS
               SIR2  99 elHGslakvkCvkcekkltaeelqeeieaekvp.....ecekcggllkpdvvf 146
                        ++H ++  ++C +c+++  + ++  + + +  +     ece+cg+ l +++++
  gene=LOC118509020 374 RVHDEMGPIQCDECQHISPNRRALVNHKVRAHGqkqayECEYCGKKLNTKLTL 426
                        66777777888888776655443333222211123344788888877766654 PP

  == domain 4  score: 6.0 bits;  conditional E-value: 0.0034
                        T-SSEEETTEEEEEEEETTTSBEEECCGGHCH.HHTTTC....BSTTTC CS
               SIR2  93 GskkvvelHGslakvkCvkcekkltaeelqee.ieaekvp...ecekcg 137
                         +++ v++HG+ +  +C  c+kkl+++ + +e +  ++     +ce cg
  gene=LOC118509020 397 LVNHKVRAHGQKQAYECEYCGKKLNTKLTLKEhLAIHTNVplySCEFCG 445
                        56667899**************999875544404433322355666665 PP

>> gene=LOC118515208  scaffold=NW_023405006.1 strand=+ Parent=rna-XM_036061904.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    0.1   0.1      0.23   1.1e+03     104     124 ..       3      23 ..       2      34 .. 0.83
   2 ?   10.9   3.8    0.0001      0.52      72     138 ..      60     125 ..      36     153 .. 0.78

  Alignments for each domain:
  == domain 1  score: 0.1 bits;  conditional E-value: 0.23
                        EEEEEETTTSBEEECCGGHCH CS
               SIR2 104 lakvkCvkcekkltaeelqee 124
                        + +++C +c++++   +l+++
  gene=LOC118515208   3 FCEFECDNCQASYADRMLRDR 23
                        67899*****99999888776 PP

  == domain 2  score: 10.9 bits;  conditional E-value: 0.0001
                        HHTTCEEEEEES-SSSHHHHTT-SSEEETT.EEEEEEEETTTSBEEECCGGHCHHHTTTC.BSTTTCC CS
               SIR2  72 ekkgkllrliTQNiDgLekkaGskkvvelH.GslakvkCvkcekkltaeelqeeieaekvpecekcgg 138
                        e+k+ + +   Q + + e + Gsk v  +   ++++v+C +c++ ++++  +++   +k  +c++cg
  gene=LOC118515208  60 EHKQLFEKSEAQSLNSVEMQDGSKDVAAIQrSDFHNVSCFNCGQAYNGS--HRRYCPAKNVNCNNCGR 125
                        455666777789999*********9999862569**********99995..45556666799****86 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (179 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1184  (0.0399191); expected 593.2 (0.02)
Passed bias filter:                      586  (0.0197572); expected 593.2 (0.02)
Passed Vit filter:                        66  (0.00222522); expected 29.7 (0.001)
Passed Fwd filter:                        18  (0.000606878); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               6  [number of targets reported over threshold]
# CPU time: 0.59u 0.01s 00:00:00.60 Elapsed: 00:00:00.32
# Mc/sec: 7224.29
//
[ok]

# 7) ZNHIT1

In [31]:
!grep PF04438 Pfam-A.hmm

ACC   PF04438.19

In [32]:
!hmmfetch Pfam-A.hmm.h3m PF04438.19 > ZNHIT1.hmm
!hmmstat ZNHIT1.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      zf-HIT               PF04438.19         87    12.24     30   1.80   1.43   1.72   0.57

In [33]:
!hmmsearch ZNHIT1.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  ZNHIT1.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       zf-HIT  [M=30]
Accession:   PF04438.19
Description: HIT zinc finger
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    1.3e-10   41.6  13.3    2.6e-10   40.7  13.3    1.5  1  gene=LOC118514154  scaffold=NC_050203.1 strand=- Parent=rna-X
    4.2e-09   36.8  10.0    9.4e-09   35.7  10.0    1.7  1  gene=LOC118505286  scaffold=NC_050202.1 strand=+ Parent=rna-X
    7.8e-08   32.8   7.3    1.1e-07   32.3   7.3    1.2  1  gene=LOC118511337  scaffold=NC_050203.1 strand=+ Parent=rna-X
    2.1e-07   31.4  14.1    3.3e-07   30.8  14.1    1.2  1  gene=LOC118517218  scaffold=NW_023405439.1 strand=+ Parent=rn
  ------ inclusion threshold ------
       0.04   14.5   3.0       0.04   14.5   3.0    1.8  2  gene=LOC118509614  scaffold=NC_050203.1 strand=- Parent=rna-X
       0.16   12.6   8.1        3.1    8.5   8.1    2.5  1  gene=LOC118509000  scaffold=NC_050203.1 strand=- Parent=rna-X
        0.2   12.2   4.5       0.44   11.2   4.5    1.5  1  gene=LOC118504299  scaffold=NC_050202.1 strand=+ Parent=rna-X
        1.1   10.0   8.6        2.8    8.6   8.6    1.7  1  gene=LOC118503753  scaffold=NC_050202.1 strand=+ Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118514154  scaffold=NC_050203.1 strand=- Parent=rna-XM_036060765.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   40.7  13.3     7e-14   2.6e-10       2      29 ..     117     144 ..     116     145 .. 0.96

  Alignments for each domain:
  == domain 1  score: 40.7 bits;  conditional E-value: 7e-14
                        --B-TTT-SB-SEE-TTT--EESSHHHH CS
             zf-HIT   2 rklCgvCgfpakYkCpkCntryCSLrCy 29
                        r++C+vCgfp+ Y+C  C+tryC++rC+
  gene=LOC118514154 117 RHFCAVCGFPSSYTCTACGTRYCCVRCL 144
                        9**************************6 PP

>> gene=LOC118505286  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036040873.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   35.7  10.0   2.5e-12   9.4e-09       3      30 .]       4      32 ..       2      32 .. 0.96

  Alignments for each domain:
  == domain 1  score: 35.7 bits;  conditional E-value: 2.5e-12
                       -B-TTT-S.B-SEE-TTT--EESSHHHHH CS
             zf-HIT  3 klCgvCgf.pakYkCpkCntryCSLrCyk 30
                       ++C +C+  +akY+Cp+Cn ++CS+ Cyk
  gene=LOC118505286  4 EICKICEVnKAKYNCPRCNLMFCSVQCYK 32
                       79**************************8 PP

>> gene=LOC118511337  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036054267.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   32.3   7.3     3e-11   1.1e-07       3      30 .]     290     319 ..     288     319 .. 0.96

  Alignments for each domain:
  == domain 1  score: 32.3 bits;  conditional E-value: 3e-11
                        -B-TT..T-SB-SEE-TTT--EESSHHHHH CS
             zf-HIT   3 klCgv..CgfpakYkCpkCntryCSLrCyk 30
                         lC++  C++ ++Y+C+++n+++CS +Cyk
  gene=LOC118511337 290 TLCAIpnCNNIKRYNCSRTNIPLCSFECYK 319
                        69***************************8 PP

>> gene=LOC118517218  scaffold=NW_023405439.1 strand=+ Parent=rna-XM_036063207.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   30.8  14.1   8.8e-11   3.3e-07       5      30 .]       5      31 ..       3      31 .. 0.97

  Alignments for each domain:
  == domain 1  score: 30.8 bits;  conditional E-value: 8.8e-11
                       -TTT-S.B-SEE-TTT--EESSHHHHH CS
             zf-HIT  5 CgvCgf.pakYkCpkCntryCSLrCyk 30
                       C++C++ + kYkC +C+ +yCS+ Cyk
  gene=LOC118517218  5 CEICNEkERKYKCKTCSLHYCSVVCYK 31
                       **************************8 PP

>> gene=LOC118509614  scaffold=NC_050203.1 strand=- Parent=rna-XM_036050440.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   -1.8   0.2       1.3   4.8e+03       5       8 ..      30      33 ..      27      37 .. 0.77
   2 ?   14.5   3.0   1.1e-05      0.04      12      29 ..      48      65 ..      45      66 .. 0.90

  Alignments for each domain:
  == domain 1  score: -1.8 bits;  conditional E-value: 1.3
                       -TTT CS
             zf-HIT  5 CgvC 8
                       C +C
  gene=LOC118509614 30 CNFC 33
                       7777 PP

  == domain 2  score: 14.5 bits;  conditional E-value: 1.1e-05
                       -SEE-TTT--EESSHHHH CS
             zf-HIT 12 akYkCpkCntryCSLrCy 29
                        kY Cp C t +C ++C+
  gene=LOC118509614 48 TKYHCPECQTNLCIVPCF 65
                       69************9998 PP

>> gene=LOC118509000  scaffold=NC_050203.1 strand=- Parent=rna-XM_036049023.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    8.5   8.1   0.00084       3.1       5      28 ..      12      49 ..      10      51 .. 0.72

  Alignments for each domain:
  == domain 1  score: 8.5 bits;  conditional E-value: 0.00084
                       -TTT-SB-SEE-TTT--E..............ESSHHH CS
             zf-HIT  5 CgvCgfpakYkCpkCntr..............yCSLrC 28
                       C++  + +kY+Cp C +                C L+C
  gene=LOC118509000 12 CAILAAAGKYSCPACPASylpvcgtdgktyanECALEC 49
                       5555569********99977766666666666666666 PP

>> gene=LOC118504299  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036038592.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   11.2   4.5   0.00012      0.44       3      26 ..      36      61 ..      35      62 .. 0.94

  Alignments for each domain:
  == domain 1  score: 11.2 bits;  conditional E-value: 0.00012
                       -B-TTT-S.B-SEE-TTT--E.ESSH CS
             zf-HIT  3 klCgvCgf.pakYkCpkCntr.yCSL 26
                       + C +Cg  ++  +C++C +  yCS+
  gene=LOC118504299 36 HQCRICGVnEGLRRCSRCQIAyYCSV 61
                       89******************99***7 PP

>> gene=LOC118503753  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036037397.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    8.6   8.6   0.00077       2.8       2      28 ..     416     443 ..     415     444 .. 0.91

  Alignments for each domain:
  == domain 1  score: 8.6 bits;  conditional E-value: 0.00077
                        --B-TTT-SB-SEE-TTT--E.ESSHHH CS
             zf-HIT   2 rklCgvCgfpakYkCpkCntr.yCSLrC 28
                        +k+Cg Cg+ a  kC++C    yCS +C
  gene=LOC118503753 416 AKVCGSCGASAAKKCSNCLLVfYCSRDC 443
                        689******8888*****9999***999 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (30 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      2326  (0.0784221); expected 593.2 (0.02)
Passed bias filter:                     1067  (0.0359744); expected 593.2 (0.02)
Passed Vit filter:                       198  (0.00667566); expected 29.7 (0.001)
Passed Fwd filter:                        80  (0.00269724); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               8  [number of targets reported over threshold]
# CPU time: 0.34u 0.02s 00:00:00.36 Elapsed: 00:00:00.21
# Mc/sec: 1839.90
//
[ok]

# 8) SAP18

In [34]:
!grep PF06487 Pfam-A.hmm

ACC   PF06487.15

In [35]:
!hmmfetch Pfam-A.hmm.h3m PF06487.15 > SAP18.hmm
!hmmstat SAP18.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      SAP18                PF06487.15        111     2.70    141   0.59   0.58   0.46   0.02

In [36]:
!hmmsearch SAP18.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  SAP18.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       SAP18  [M=141]
Accession:   PF06487.15
Description: Sin3 associated polypeptide p18 (SAP18)
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
      8e-37  127.3   0.0      1e-36  126.9   0.0    1.2  1  gene=LOC118506822  scaffold=NC_050202.1 strand=- Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118506822  scaffold=NC_050202.1 strand=- Parent=rna-XM_036044551.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  126.9   0.0   3.5e-41     1e-36       7     141 .]       1     111 [.       1     111 [. 0.97

  Alignments for each domain:
  == domain 1  score: 126.9 bits;  conditional E-value: 3.5e-41
              SAP18   7 ttPfLLrlFvktgsfhrldeFsssgslpsdelqiytWkdctLrELaqllasalpsllpspavgtrlaFrlvypdtrkrgryaskdlGsvvig 98
                        t+P+LLr+F++tg++h+++e+s  g++ps+elqiytW+d+tLrEL++l++++   +++++++gt + F++vypd+     y+++++G +++g
  gene=LOC118506822   1 TCPLLLRVFCSTGRHHSTNEYS-YGNVPSNELQIYTWMDATLRELTTLVRDV---NPETRRKGTYFDFAVVYPDRG--SMYRMREIGVTCSG 86
                        8*********************.9****************************...9*******************7..69************ PP

              SAP18  99 ekgseaeddseeeeeeerseeedadktLadlrfviGDyidvaI 141
                        +kg+   dd+               ktLa+++f+iGD++d+ I
  gene=LOC118506822  87 QKGA---DDA---------------KTLAQAKFTIGDFMDINI 111
                        ****...564...............***************987 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (141 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1444  (0.0486851); expected 593.2 (0.02)
Passed bias filter:                      843  (0.0284221); expected 593.2 (0.02)
Passed Vit filter:                        52  (0.0017532); expected 29.7 (0.001)
Passed Fwd filter:                         1  (3.37154e-05); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               1  [number of targets reported over threshold]
# CPU time: 0.45u 0.01s 00:00:00.46 Elapsed: 00:00:00.25
# Mc/sec: 7396.60
//
[ok]

# 9)PRMT8

In [37]:
!grep PF06325 Pfam-A.hmm

ACC   PF06325.16

In [38]:
!hmmfetch Pfam-A.hmm.h3m PF06325.16 > PRMT8.hmm
!hmmstat PRMT8.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# idx  name                 accession        nseq eff_nseq      M relent   info p relE compKL
# ---- -------------------- ------------ -------- -------- ------ ------ ------ ------ ------
1      PrmA                 PF06325.16         27     1.53    295   0.59   0.59   0.51   0.02

In [39]:
!hmmsearch PRMT8.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  PRMT8.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       PrmA  [M=295]
Accession:   PF06325.16
Description: Ribosomal protein L11 methyltransferase (PrmA)
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    8.9e-14   52.3   0.7    1.5e-13   51.6   0.7    1.3  1  gene=LOC118508889  scaffold=NC_050203.1 strand=+ Parent=rna-X
    5.7e-10   39.8   0.1    1.5e-09   38.4   0.1    1.7  1  gene=LOC118504700  scaffold=NC_050202.1 strand=+ Parent=rna-X
    7.3e-10   39.5   0.1    1.2e-09   38.8   0.1    1.2  1  gene=LOC118508587  scaffold=NC_050202.1 strand=- Parent=rna-X
    2.7e-09   37.6   0.0    2.7e-09   37.6   0.0    1.5  1  gene=LOC118502676  scaffold=NC_050202.1 strand=+ Parent=rna-X
    2.7e-09   37.6   0.0    2.7e-09   37.6   0.0    1.5  1  gene=LOC118502704  scaffold=NC_050202.1 strand=+ Parent=rna-X
      3e-08   34.2   0.1    4.4e-07   30.3   0.1    2.1  2  gene=LOC118514218  scaffold=NC_050203.1 strand=- Parent=rna-X
    8.8e-08   32.6   0.1    1.2e-07   32.2   0.1    1.1  1  gene=LOC118506044  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.1e-06   29.1   0.0    1.6e-06   28.5   0.0    1.2  1  gene=LOC118516408  scaffold=NW_023405224.1 strand=+ Parent=rn
    1.2e-06   28.9   0.0    2.2e-06   28.0   0.0    1.4  1  gene=LOC118511052  scaffold=NC_050203.1 strand=+ Parent=rna-X
    0.00012   22.3   0.0    0.00018   21.8   0.0    1.2  1  gene=LOC118512749  scaffold=NC_050203.1 strand=+ Parent=rna-X
    0.00028   21.1   0.0    0.00052   20.2   0.0    1.4  2  gene=LOC118510753  scaffold=NC_050203.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517473  scaffold=NC_050201.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
     0.0083   16.3   0.0      0.013   15.7   0.0    1.3  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
  ------ inclusion threshold ------
      0.011   15.9   0.0      0.016   15.4   0.0    1.2  1  gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-X
      0.028   14.5   0.0      0.053   13.7   0.0    1.3  1  gene=LOC118507371  scaffold=NC_050202.1 strand=- Parent=rna-X
      0.041   14.0   0.0      0.076   13.1   0.0    1.4  1  gene=LOC118514289  scaffold=NC_050203.1 strand=+ Parent=rna-X
      0.044   13.9   0.0      0.061   13.5   0.0    1.2  1  gene=LOC118502774  scaffold=NC_050202.1 strand=- Parent=rna-X
       0.14   12.3   0.0       0.23   11.6   0.0    1.3  1  gene=LOC118504836  scaffold=NC_050202.1 strand=+ Parent=rna-X
       0.26   11.4   0.0       0.33   11.0   0.0    1.1  1  gene=LOC118513882  scaffold=NC_050203.1 strand=- Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118508889  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036048692.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   51.6   0.7   1.1e-16   1.5e-13     159     216 ..     210     268 ..     199     293 .. 0.82

  Alignments for each domain:
  == domain 1  score: 51.6 bits;  conditional E-value: 1.1e-16
               PrmA 159 vkegeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkvee.klevy 216
                        v +g++vlDvG+G G  aiaa+++ga++v+a D+D+vA++a+  NaelN++++ +l v
  gene=LOC118508889 210 VFHGKSVLDVGCGCGASAIAALMVGARHVTANDIDPVALQATLLNAELNGITSnRLAVS 268
                        55789**********************************************99566552 PP

>> gene=LOC118504700  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036039534.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   38.4   0.1   1.1e-12   1.5e-09     160     232 ..     282     356 ..     273     377 .. 0.84

  Alignments for each domain:
  == domain 1  score: 38.4 bits;  conditional E-value: 1.1e-12
               PrmA 160 kegeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkvee.klevy...lseellkekadvvvaN 232
                         ++++vlD+G+G++iL++ a+k gak+v+ vD  ++ +  a + +++N++++ ++ v+     +el+ ek+d++v+
  gene=LOC118504700 282 MKDKTVLDLGCGTAILSMFASKAGAKEVISVDQSDI-IYQAMDIVRKNNIDNiRF-VKgrlEDTELPVEKVDIIVSE 356
                        5789****************************9998.667788899999999555.743323567778*******85 PP

>> gene=LOC118508587  scaffold=NC_050202.1 strand=- Parent=rna-XM_036048489.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   38.8   0.1   9.1e-13   1.2e-09     160     231 ..      81     157 ..      73     172 .. 0.83

  Alignments for each domain:
  == domain 1  score: 38.8 bits;  conditional E-value: 9.1e-13
               PrmA 160 kegeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkveeklevylseellk.......ekadvvva 231
                         +g+ vlD+G+G+GiL++ aak ga+kv+a+   ++ ++ a++ +e N+++e +++  ++++ +        k+d++++
  gene=LOC118508587  81 FKGKIVLDIGCGTGILSMFAAKAGAAKVIAIECSNI-IDYAQKIIEANNLQETITLV-KGKVEEvtlpdgcDKVDIIIS 157
                        57899****************************987.9**************88763.222222335668899999997 PP

>> gene=LOC118502676  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036035246.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   37.6   0.0   2.1e-12   2.7e-09     161     232 ..     163     236 ..     152     265 .. 0.82

  Alignments for each domain:
  == domain 1  score: 37.6 bits;  conditional E-value: 2.1e-12
               PrmA 161 egeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkveeklevylseellk....ekadvvvaN 232
                        +++ vlDvG+GSGiL+  a++ ga+kv+av   ++A + a++ ++ N++++k+ v++ +++ +    e++dv+++
  gene=LOC118502676 163 QNKVVLDVGAGSGILSFFAVQAGAAKVYAVEASNMA-QYAQQLVSSNNLTDKIIVIA-GKIEEielpEHVDVIISE 236
                        567899*****************************9.78899999999999886642.33322335699****975 PP

>> gene=LOC118502704  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036035248.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   37.6   0.0   2.1e-12   2.7e-09     161     232 ..     163     236 ..     152     265 .. 0.82

  Alignments for each domain:
  == domain 1  score: 37.6 bits;  conditional E-value: 2.1e-12
               PrmA 161 egeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkveeklevylseellk....ekadvvvaN 232
                        +++ vlDvG+GSGiL+  a++ ga+kv+av   ++A + a++ ++ N++++k+ v++ +++ +    e++dv+++
  gene=LOC118502704 163 QNKVVLDVGAGSGILSFFAVQAGAAKVYAVEASNMA-QYAQQLVSSNNLTDKIIVIA-GKIEEielpEHVDVIISE 236
                        567899*****************************9.78899999999999886642.33322335699****975 PP

>> gene=LOC118514218  scaffold=NC_050203.1 strand=- Parent=rna-XM_036060926.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   30.3   0.1   3.4e-10   4.4e-07     161     219 ..      55     113 ..      42     141 .. 0.79
   2 ?    1.4   0.0      0.21   2.8e+02     154     212 ..     399     457 ..     394     476 .. 0.78

  Alignments for each domain:
  == domain 1  score: 30.3 bits;  conditional E-value: 3.4e-10
               PrmA 161 egeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkveeklevylse 219
                        ++++vlD+GtGSG+L++ a + ga++vva+       + a++ +e N+++e++++  ++
  gene=LOC118514218  55 QQAHVLDIGTGSGLLSMMAIRAGADSVVACEAFRPMAECAEKVIEANGMKERIRLVKKR 113
                        4669***************************999999**************99874332 PP

  == domain 2  score: 1.4 bits;  conditional E-value: 0.21
               PrmA 154 aleklvkegeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkvee.k 212
                         +e++  +++ vl +  GS +L +aaa++g+kkv+ +  + ++ +  +  +e N+v + +
  gene=LOC118514218 399 YFERVFSSDSVVLVLSEGS-LLGLAAARMGVKKVLLYEPNAISRRCMEAFVEHNSVPNvQ 457
                        5667777777777777776.8*************99998888888888888888887644 PP

>> gene=LOC118506044  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036042673.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   32.2   0.1   8.9e-11   1.2e-07     161     260 ..      95     203 ..      79     232 .. 0.76

  Alignments for each domain:
  == domain 1  score: 32.2 bits;  conditional E-value: 8.9e-11
               PrmA 161 egeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkvee..klevyl...seellk.....ekadvvvaNILaevl...i 239
                        ++ ++l vG+G GiL+ a akl+  kvv++D  e  +++ak+ a+  k  +  +++ ++   ++   +     e++d vva  + e +   +
  gene=LOC118506044  95 ANLNILEVGCGGGILTEALAKLNS-KVVGIDPSEKLINVAKQHAKDDKSLDpeQIQYHVetiEQ---HaaknaERYDAVVASEVLEHVndkV 182
                        45589*****************96.799****************99976553444433211122...123466999****976655552335 PP

               PrmA 240 elaedikkllkeggllilSGi 260
                        +++e+  ++lk+gg + +  i
  gene=LOC118506044 183 AFIEQCLAALKPGGSMFITTI 203
                        799***********9877665 PP

>> gene=LOC118516408  scaffold=NW_023405224.1 strand=+ Parent=rna-XM_036062272.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   28.5   0.0   1.3e-09   1.6e-06     161     258 ..     108     213 ..      96     221 .. 0.78

  Alignments for each domain:
  == domain 1  score: 28.5 bits;  conditional E-value: 1.3e-09
               PrmA 161 egeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelN.kveeklevy..lseellk...ekadvvv.aNILaevlie..lae 243
                        +g ++lDvG+G Gi + a akl a +vv++D     +++ak  ae+  +++e+++ y    ++  +   +k+dvvv +  + +++ +  l++
  gene=LOC118516408 108 KGLTILDVGCGGGIYTEALAKLHA-TVVGIDPARHLIEVAKAHAEKQpDIKERCQYYeqSLDDHWQgavGKYDVVVlSETIEHMVDQstLLK 198
                        5669******************98.599*************99987658999998753223333335669***9982445555554233777 PP

               PrmA 244 dikkllkeggllilS 258
                        +++++lk+gg + +S
  gene=LOC118516408 199 QVAAVLKPGGSVFIS 213
                        899999999999887 PP

>> gene=LOC118511052  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036053653.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   28.0   0.0   1.7e-09   2.2e-06     155     234 ..     157     241 ..     154     271 .. 0.75

  Alignments for each domain:
  == domain 1  score: 28.0 bits;  conditional E-value: 1.7e-09
               PrmA 155 leklvkege.evlDvGtGSGiLaiaaak.lgakkvvavDlDevAvkaakeNaelNkveeklevyl..seellk..ekadvvvaNIL 234
                        +e+++ eg  evlD+GtG+G+L++ a++  g +k+ a+D  e+ v++a++ +  N++++++ +++  s++l k  e++ ++v   L
  gene=LOC118511052 157 IESQIAEGYnEVLDIGTGTGLLSMYALQcAGIRKAAACDGSEIMVQIARDVFGANGLSDRICLFQsySQDL-KigERFSLIVTETL 241
                        56555544439*************988725899**************************997754114444.23588888887666 PP

>> gene=LOC118512749  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036057641.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   21.8   0.0   1.4e-07   0.00018     156     209 ..      57     110 ..      50     135 .. 0.82

  Alignments for each domain:
  == domain 1  score: 21.8 bits;  conditional E-value: 1.4e-07
               PrmA 156 eklvkegeevlDvGtGSGiLaiaaaklgakkvvavDlDevAvkaakeNaelNkv 209
                        e+ +k +++++D+G+G G++ i  a+ g k+ +++D+ + A++ ak   +  k
  gene=LOC118512749  57 EDKIKVDDSIIDLGCGNGMMLIELAQEGFKNLTGIDYSPKAIELAKAICADQKY 110
                        56688999*************************************976655555 PP

>> gene=LOC118510753  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036053000.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   20.2   0.0     4e-07   0.00052     162     232 ..      40     117 ..      24     119 .. 0.73
   2 ?   -3.8   0.0       8.2   1.1e+04     242     274 ..     164     196 ..     161     204 .. 0.71

  Alignments for each domain:
  == domain 1  score: 20.2 bits;  conditional E-value: 4e-07
               PrmA 162 ge..evlDvGtGSGiLaiaaakl...gakkvvavDlDevAvkaakeNaelNkveeklevy..lseellkekadvvvaN 232
                        ++    + +G GSG+L +a  k    g ++ ++ D+++ A +++++  +lN++++   v+  l ++l ++ +d++v N
  gene=LOC118510753  40 RQplLCVEIGPGSGVLIVALEKHlpsGRSHFIGFDINPNACQMTQKTCQLNGTASVDVVNmdLLAGLRTACVDLLVFN 117
                        33235569***********88743448999*********************999844354225666667778888766 PP

  == domain 2  score: -3.8 bits;  conditional E-value: 8.2
               PrmA 242 aedikkllkeggllilSGilkekaeevkealeq 274
                        ++d+ ++l + g++ l  + ++k eev +++e+
  gene=LOC118510753 164 LDDLDRILSPRGVFYLLLLKENKPEEVLKQMER 196
                        677778888888888777777777778777765 PP

>> gene=LOC118517473  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063658.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517473  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063654.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063655.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063656.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063657.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063659.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.0   9.9e-06     0.013     151     182 ..      70     101 ..      64     156 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 9.9e-06
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  70 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 101
                        6999*******************998665554 PP

>> gene=LOC118517474  scaffold=NC_050201.1 strand=+ Parent=rna-XM_036063653.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   15.4   0.0   1.2e-05     0.016     151     182 ..      96     127 ..      91     181 .. 0.80

  Alignments for each domain:
  == domain 1  score: 15.4 bits;  conditional E-value: 1.2e-05
               PrmA 151 clealeklvkegeevlDvGtGSGiLaiaaakl 182
                        +le+l+ ++k++++vlDvG GSG L+   a++
  gene=LOC118517474  96 ALELLQPYLKPNSKVLDVGSGSGYLTACFARF 127
                        6999*******************998665554 PP

>> gene=LOC118507371  scaffold=NC_050202.1 strand=- Parent=rna-XM_036045810.1

#10) TDG

In [40]:
!grep PF03167 Pfam-A.hmm

ACC   PF03167.22

In [41]:
!hmmfetch Pfam-A.hmm.h3m PF03167.22 > TDG.hmm
!hmmstat TGD.hmm

# hmmstat :: display summary statistics for a profile file
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Error: File existence/permissions problem in trying to open HMM file TGD.hmm.
HMM file TGD.hmm not found (nor an .h3m binary of it)

In [42]:
!hmmsearch TDG.hmm proteins.fasta

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  TDG.hmm
# target sequence database:        proteins.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       UDG  [M=155]
Accession:   PF03167.22
Description: Uracil DNA glycosylase superfamily
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    2.9e-07   31.3   0.0    3.7e-07   31.0   0.0    1.1  1  gene=LOC118504424  scaffold=NC_050202.1 strand=- Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118504424  scaffold=NC_050202.1 strand=- Parent=rna-XM_036038860.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   31.0   0.0   1.2e-11   3.7e-07      74     151 ..       4      76 ..       2      79 .. 0.82

  Alignments for each domain:
  == domain 1  score: 31.0 bits;  conditional E-value: 1.2e-11
                        CCCCTCCHH.HHHHHHHHHHSSEEEEESHHHHHH..HHHHSCESCCCSCT.SEEEEES-SSTTTTTTTTSHHHHHHHHH CS
                UDG  74 saeiaacap.lleeeiellkprvivllGktaakallgeklgklrgklleakirvlplphPsplnrnffksnpelkaeaw 151
                        + ei+  ++ +l++ + llkp+++v +G++  +++   k+ +  +  l++ i  + +phPsp++ n  ++n ++ka+ w
  gene=LOC118504424   4 KGEIQSISEqFLAKALTLLKPKIVVSVGRYTEDRV---KTLSK-QNKLDPAIVTYCMPHPSPRSLN--NTNWPEKAKLW 76
                        6789999999************************8...22222.4444444999************..89999999988 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (155 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                       642  (0.0216453); expected 593.2 (0.02)
Passed bias filter:                      474  (0.0159811); expected 593.2 (0.02)
Passed Vit filter:                        42  (0.00141605); expected 29.7 (0.001)
Passed Fwd filter:                         1  (3.37154e-05); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               1  [number of targets reported over threshold]
# CPU time: 0.38u 0.01s 00:00:00.39 Elapsed: 00:00:00.39
# Mc/sec: 5210.82
//
[ok]

In [43]:
families = {
    'ALKBH1': 'alkbh1.hmm',
    'BAP1': 'bap1.hmm',
    'HDAC11': 'HDAC11.hmm',
    'EEF1AKMT4': 'EEF1AKMT4.hmm',
    'SUDS3': 'SUDS3.hmm',
    'SIRT2': 'SIRT2.hmm',
    'ZNHIT1': 'ZNHIT1.hmm',
    'SAP18': 'SAP18.hmm',
    'PRMT8': 'PRMT8.hmm',
    'TDG': 'TDG.hmm'
}

results = []

for family, hmm_file in families.items():
    !hmmsearch --tblout temp_output.txt {hmm_file} proteins.fasta

    with open('temp_output.txt', 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split()
            if len(parts) >= 3 and not parts[0].startswith('#'):
                gene_name = parts[0]
                results.append({
                    'Проверяемое семейство': family,
                    'Название гена': gene_name.split('=')[1] if '=' in gene_name else gene_name,
                })

df_results = pd.DataFrame(results)
print(df_results)

df_results.to_csv('epigenetic_genes.csv', index=False)

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  alkbh1.hmm
# target sequence database:        proteins.fasta
# per-seq hits tabular output:     temp_output.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       2OG-FeII_Oxy_2  [M=194]
Accession:   PF13532.9
Description: 2OG-Fe(II) oxygenase superfamily
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    4.2e-23   83.2   0.0    8.4e-23   82.2   0.0    1.5  1  gene=LOC118508064  scaffold=NC_050202.1 strand=+ Parent=rna-X
      2e-14   54.9   0.0    3.2e-13   51.0   0.0    1.9  2  gene=LOC118502523  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.4e-12   48.9   0.0    1.2e-11   45.8   0.0    1.9  1  gene=LOC118516394  scaffold=NW_023405219.1 strand=+ Parent=rn


Domain annotation for each sequence (and alignments):
>> gene=LOC118508064  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036047522.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   82.2   0.0   8.5e-27   8.4e-23      18     194 .]     140     323 ..     135     323 .. 0.80

  Alignments for each domain:
  == domain 1  score: 82.2 bits;  conditional E-value: 8.5e-27
     2OG-FeII_Oxy_2  18 lkelleegpfrqptilggkrvsvqqtlcgtlrwat.dgpkyrysekrsvkskpf.spfpeallqlverlvkeag.peglspnaalvnfYsdg 106
                        ++e++e++     ++   ++ ++q +   + r++   g++  y + +++k kp+ +++p++  +l++rl +    ++ + p+++ vn+Y++g
  gene=LOC118508064 140 IDEAMEKVLLEAVNCDDSEATDLQFKKTLKHRKVKhFGYEFVYGTNNVDKTKPLeRKIPAVCDELWKRLQNLHPeLRWHVPDQLTVNHYDPG 231
                        566666666666667766676776643333333330347777887766666666368999999******986655677789*********** PP

     2OG-FeII_Oxy_2 107 ariglHqDkeesalgapivSlSLGasatflfgtesreeeiiallLesgdllvmggesrkay.Hgvprikkdtapeq.....selesrRinlT 192
                        + i  H+D  ++ +++pi+SlSLG+ +++ f++   + ++  + L+  +ll+mggesr+ + Hg+++ k dt p +      + ++ R++lT
  gene=LOC118508064 232 QGIPPHVDTHSA-FDDPILSLSLGSDVVMEFKQP-FSGKQVCVDLPARSLLIMGGESRYDWtHGITPRKMDTVPASnggltVRKRKLRVSLT 321
                        **********88.*******************97.55567779****************************999999999966699****** PP

     2OG-FeII_Oxy_2 193 fR 194
                        fR
  gene=LOC118508064 322 FR 323
                        *9 PP

>> gene=LOC118502523  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036034788.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    2.6   0.0     0.022   2.1e+02       2      28 ..      15      43 ..      14      53 .. 0.79
   2 !   51.0   0.0   3.2e-17   3.2e-13      58     194 .]      52     213 ..      38     213 .. 0.85

  Alignments for each domain:
  == domain 1  score: 2.6 bits;  conditional E-value: 0.022
     2OG-FeII_Oxy_2  2 lllipnflseeeaaellkelleegp..fr 28
                       ++++p+f+++ee  +++++++++ +  ++
  gene=LOC118502523 15 VYYVPDFITKEEECSIMQAIDKTPKprWT 43
                       89****************99955442344 PP

  == domain 2  score: 51.0 bits;  conditional E-value: 3.2e-17
     2OG-FeII_Oxy_2  58 rysekrsvkskpfspfpeallqlverlvkeag.peglspnaalvnfYsdgariglHqDkeesalgapivSlSLGasatflfgtesree.... 144
                        +y ++ + k+  ++++p+ l++ +er+ +     +g ++n++l+n Y +g+ i+ H D     + ++i ++S G+ a++ + +++++
  gene=LOC118502523  52 NYGGVPHPKGMIAEDIPAWLTRYIERVNQLNVyEDGIKANHVLINEYLPGQGIMPHLDGP-L-FYPTITTISCGSHAVLEYYDQTEDSesps 141
                        566666667777899************997774559***********************9.3.78****************98876666899 PP

     2OG-FeII_Oxy_2 145 .......eiiallLesgdllvmggesrkay.Hgvprikkdtapeq..............selesrRinlTfR 194
                                +  + Le+ +ll+ + ++ + y H+++  ++d  +                   +++Ri+lT+R
  gene=LOC118502523 142 ngplvrhHVANIVLEPRSLLIVKDDMYHKYlHAIAELEQDVIDDKaanlsmlnsvsvgdVLQRTKRISLTIR 213
                        9*****99********************************44444455566777778885669*******99 PP

>> gene=LOC118516394  scaffold=NW_023405219.1 strand=+ Parent=rna-XM_036062255.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   45.8   0.0   1.3e-15   1.2e-11      55     194 .]      49     212 ..      14     212 .. 0.83

  Alignments for each domain:
  == domain 1  score: 45.8 bits;  conditional E-value: 1.3e-15
     2OG-FeII_Oxy_2  55 pkyrysekrsvkskpfspfpeallqlverlvkeag.peglspnaalvnfYsdgariglHqDkeesalgapivSlSLGasatflfgtesree. 144
                        +  +y ++ + k+  ++++p+ l++ +er+ +     +g ++n++l+n Y +g+ i+ H D     l  p  ++S G+ a++ + +++++
  gene=LOC118516394  49 RLINYGGVPHPKGMIAEDIPAWLTRYIERVNQLNVyEDGIKANHVLINEYLPGQGIMPHLDGP---LFYPTTTISCGSHAVLEYYDQTEDSe 137
                        55577777777888899*************997774559***********************9...44799*************98876666 PP

     2OG-FeII_Oxy_2 145 ..........eiiallLesgdllvmggesrkay.Hgvprikkdtapeq..............selesrRinlTfR 194
                                   +  + Le+ +ll+ + ++ + y H+++  ++d  +                   +++Ri+lT+R
  gene=LOC118516394 138 spsngplvrhHVANIVLEPRSLLIVKDDMYHKYlHAIAELEQDVIDDKaanlsmlnsvsvgdVLQRTKRISLTIR 212
                        8999*****99********************************44444455566777778885669*******99 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (194 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1311  (0.0442009); expected 593.2 (0.02)
Passed bias filter:                      407  (0.0137222); expected 593.2 (0.02)
Passed Vit filter:                        35  (0.00118004); expected 29.7 (0.001)
Passed Fwd filter:                        10  (0.000337154); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               3  [number of targets reported over threshold]
# CPU time: 0.57u 0.01s 00:00:00.57 Elapsed: 00:00:00.33
# Mc/sec: 7688.14
//
[ok]
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  bap1.hmm
# target sequence database:        proteins.fasta
# per-seq hits tabular output:     temp_output.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Peptidase_C12  [M=211]
Accession:   PF01088.24
Description: Ubiquitin carboxyl-terminal hydrolase, family 1
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    8.3e-70  235.5   0.0    1.3e-69  234.9   0.0    1.3  1  gene=LOC118512888  scaffold=NC_050203.1 strand=+ Parent=rna-X
      7e-66  222.7   0.0    1.6e-65  221.5   0.0    1.7  1  gene=LOC118508022  scaffold=NC_050202.1 strand=- Parent=rna-X
    2.1e-42  146.0   0.4    2.3e-42  145.9   0.4    1.0  1  gene=LOC118503994  scaffold=NC_050202.1 strand=- Parent=rna-X
  ------ inclusion threshold ------
      0.038   14.4   0.0      0.058   13.9   0.0    1.2  1  gene=LOC118510116  scaffold=NC_050203.1 strand=+ Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118512888  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036057987.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  234.9   0.0   1.8e-73   1.3e-69       1     210 [.       8     208 ..       8     209 .. 0.91

  Alignments for each domain:
  == domain 1  score: 234.9 bits;  conditional E-value: 1.8e-73
                        ---EE--HHHHHHHHHHHT--S..EEEE--S.SHHHTTS.---EEEEEEE.----------.---------..T...TS------STTGHHH CS
      Peptidase_C12   1 wlplEsdpevftelleklGvkgvqfeevyslddellasl.pvygliflfkyieeeeeeekrekeeeekdeeeeevsekvfFakQtiqnaCgt 91
                        w+ +Esdp+vftel++++Gv+gvq+ee++sld+++++ l pv+gl+flfk+++++ e + +  +    d    +  ek+fFakQ+i+naC+t
  gene=LOC118512888   8 WCLIESDPGVFTELIKEFGVDGVQVEELWSLDEDSFKDLePVHGLVFLFKWVKDD-EPAGSIVQ----D----SRLEKIFFAKQVINNACAT 90
                        *******************************999*999988***********988.44433222....2....23567************** PP

                        HHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHH...HHS--EEEEEEEEETTEEEEE-T CS
      Peptidase_C12  92 iAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapee...eedvafHFiafvpvdgrlyeLDG 180
                        +A+L++llN  +++++i+lg +L++fkef+ ++++ ++g al+n ++ir++hnsfa+++  e +++   +ed  fHF+ +vpvdgrlyeLDG
  gene=LOC118512888  91 QAILSILLN--ATHSDINLGATLTDFKEFACTFDAYNKGLALSNASQIRTVHNSFARQTLFELDNKssgKED-VFHFVGYVPVDGRLYELDG 179
                        *********..568999***************************************9888777766777778.8****************** PP

                        TS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 181 lkegPidlgeleeeeedledavrkviqeri 210
                        lkegPid+g++  +++d+ ++vr++i++r+
  gene=LOC118512888 180 LKEGPIDHGAV-GSGQDWLKVVRPIIEKRM 208
                        ***********.578*************98 PP

>> gene=LOC118508022  scaffold=NC_050202.1 strand=- Parent=rna-XM_036047414.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  221.5   0.0   2.2e-69   1.6e-65       1     210 [.      12     221 ..      12     222 .. 0.87

  Alignments for each domain:
  == domain 1  score: 221.5 bits;  conditional E-value: 2.2e-69
                        ---EE--HHHHHHHHHHHT--S..EEEE--S.SHHHTTS---EEEEEEE.----------.-----.----..T...TS------STTGHHH CS
      Peptidase_C12   1 wlplEsdpevftelleklGvkgvqfeevyslddellaslpvygliflfkyieeeeeeekrekeeee.kdeeeeevsekvfFakQtiqnaCgt 91
                        wl+lEsdp++ft l+e++Gvkgvq+ee+y+l++  l+  +vyg+iflf++iee++ ++k   e+++ + ++e+   +++fFa+Q+++n+C+t
  gene=LOC118508022  12 WLELESDPGLFTLLMEDFGVKGVQVEEIYDLQK-NLEG-QVYGFIFLFRWIEERRARRKI-VETTDiYVKDEDA-VNNIFFAQQVVPNSCAT 99
                        9******************************54.4433.6************99888876.4444444444334.557************** PP

                        HHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHH.........HHS--EEEEEEEEETTE CS
      Peptidase_C12  92 iAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapee.........eedvafHFiafvpvdgr 174
                        +AlL+vllN++    +ielg +L+++k +tkg+spe++g a++n++e++ ahns+a ++  +  ++         + + afHF++fvp+dgr
  gene=LOC118508022 100 HALLSVLLNCS----DIELGLTLSRLKMHTKGMSPENKGWAIGNTPELACAHNSHAMPQARRRMDRnsgvstgrfTGE-AFHFVSFVPIDGR 186
                        *********99....89***************************************7665544444678888887667.9************ PP

                        EEEE-TTS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 175 lyeLDGlkegPidlgeleeeeedledavrkviqeri 210
                        l+eLDGlk++P+d+g++  e+e ++d++r+v+ +r+
  gene=LOC118508022 187 LFELDGLKPFPMDHGPW-GEKEAWTDKFRRVMSDRL 221
                        *****************.4679*********99885 PP

>> gene=LOC118503994  scaffold=NC_050202.1 strand=- Parent=rna-XM_036037962.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  145.9   0.4   3.1e-46   2.3e-42      60     210 ..       5     151 ..       1     152 [. 0.87

  Alignments for each domain:
  == domain 1  score: 145.9 bits;  conditional E-value: 3.1e-46
                        -.---------..T...TS------STTGHHHHHHHHHHHH..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..-- CS
      Peptidase_C12  60 rekeeeekdeeeeevsekvfFakQtiqnaCgtiAlLhvllNleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegq 151
                        r+ke+ee + ++ e+ +++fF +Q ++naCgtiA++h++lN  n + eie+gs+Lkk+++ +k+lsp++rge+l+++  ++ +h++ a+egq
  gene=LOC118503994   5 RAKEDEELKAKNVEHPKSLFFTRQFVHNACGTIAVIHAILN--NPDIEIEEGSVLKKYFDGAKDLSPDDRGELLNKNVDLKATHEENAQEGQ 94
                        223444433334556789***********************..557888******************************************* PP

                        -SSTHHHHS--EEEEEEEEETTEEEEE-TTS.S-EEEEE--T..TTHHHH.HHHHHHHT CS
      Peptidase_C12 152 teapeeeedvafHFiafvpvdgrlyeLDGlkegPidlgeleeeeedledavrkviqeri 210
                        t++p+ ++ v +HFiafv+v+g+lyeLDG+k++P+ +g++++  e+l + + +v++++i
  gene=LOC118503994  95 TATPNINDAVYHHFIAFVEVEGTLYELDGRKNFPVAHGKTTP--ETLLKDAVQVCKKFI 151
                        ****999999******************************65..67866668****998 PP

>> gene=LOC118510116  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036051583.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?   13.9   0.0   7.8e-06     0.058     100     164 ..      31      90 ..      18      95 .. 0.80

  Alignments for each domain:
  == domain 1  score: 13.9 bits;  conditional E-value: 7.8e-06
                        H..STS--.-TTSHHHHHHHHHTTS-HHHHHHHHHT-HHHHHHHTTSC..---SSTHHHHS--EE CS
      Peptidase_C12 100 NleneaeeielgseLkkfkeftkglspeergealenseeirkahnsfasegqteapeeeedvafH 164
                        +++    ++e  + ++++ e++++++ ++r+ ++e+  ++++ h+++ + + ++ap+ e++  +H
  gene=LOC118510116  31 ECD---LDLEDPNIISRLPEQCQNVDDATRALMVEEAASFKQFHQKLLDYEASQAPATEDE--VH 90
                        544...456778899*********************************9999999977554..44 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (211 nodes)
Target sequences:                      29660  (13143255 residues searched)
Passed MSV filter:                      1609  (0.0542481); expected 593.2 (0.02)
Passed bias filter:                      583  (0.0196561); expected 593.2 (0.02)
Passed Vit filter:                        35  (0.00118004); expected 29.7 (0.001)
Passed Fwd filter:                         4  (0.000134862); expected 0.3 (1e-05)
Initial search space (Z):              29660  [actual number of targets]
Domain search space  (domZ):               4  [number of targets reported over threshold]
# CPU time: 0.51u 0.01s 00:00:00.52 Elapsed: 00:00:00.27
# Mc/sec: 10120.57
//
[ok]
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  HDAC11.hmm
# target sequence database:        proteins.fasta
# per-seq hits tabular output:     temp_output.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       Hist_deacetyl  [M=307]
Accession:   PF00850.22
Description: Histone deacetylase domain
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence          Description
    ------- ------ -----    ------- ------ -----   ---- --  --------          -----------
    6.2e-89  299.1   0.1    8.1e-89  298.7   0.1    1.1  1  gene=LOC118511268  scaffold=NC_050203.1 strand=+ Parent=rna-X
    2.7e-88  297.0   0.4    3.4e-88  296.7   0.4    1.1  1  gene=LOC118517556  scaffold=NC_050202.1 strand=+ Parent=rna-X
    1.1e-82  278.6   0.0    1.1e-82  278.6   0.0    2.3  3  gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-X
    1.2e-82  278.5   0.0    1.2e-82  278.5   0.0    2.3  2  gene=LOC118510456  scaffold=NC_050201.1 strand=+ Parent=rna-X
    1.2e-82  278.5   0.0    1.2e-82  278.5   0.0    2.3  2  gene=LOC118510450  scaffold=NC_050201.1 strand=+ Parent=rna-X
    4.7e-54  184.6   0.0    5.9e-54  184.2   0.0    1.1  1  gene=LOC118505081  scaffold=NC_050202.1 strand=+ Parent=rna-X


Domain annotation for each sequence (and alignments):
>> gene=LOC118511268  scaffold=NC_050203.1 strand=+ Parent=rna-XM_036051029.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  298.7   0.1   1.6e-92   8.1e-89       1     305 [.      26     315 ..      26     317 .. 0.93

  Alignments for each domain:
  == domain 1  score: 298.7 bits;  conditional E-value: 1.6e-92
                        SSSGTCHHHHHHHHHHHT.TCCHHCCEEEE-----HHHHTTTS-HHHHHHHHHHHHHCHHCHTTHCCHHHCCCCCCSSSCHCTSTCCHHHHH CS
      Hist_deacetyl   1 hpespeRlsailealaeaeglldkleliidpreatkeellrvHseeYlelleelteelkkkeeaselelskseskedddtylspgsleaakl 92
                        hp++p+R++ ++++l  ++gl +k+e+ ++p++at +e++++Hs++Y+++l++   +  ++ +++   +++ +    +d+++++g++e+++l
  gene=LOC118511268  26 HPMKPHRIR-MTHNLLLNYGLYRKMEI-YRPHKATADEMTKFHSDDYIRFLRSIRPDNMSEYNKH---MQRFN--VGEDCPVFDGLYEFCQL 110
                        9********.666666668***99885.************************9887766665333...33333..4678************* PP

                        HHHHHHHHHHHHHTTSSSEEEETT.SS--TT-BSSB-BTTBSS-HHHHHHHHHHHTTTSS-EEEEE-SSS--HHHHHHCTT-SSEEEEEEEE CS
      Hist_deacetyl  93 aagavleavdavlegevrsafalv.rPpgHHAekdkasGFCllNnvaiaakylqkkyglkrvaivDfDvHhGnGtqeifysdpsvltlSiHr 183
                        +ag++++a+ ++ ++   s+++++  +++HHA+k++asGFC++N++++++ +l k y ++rv+++D+DvHhG+G++e+fy +++v+t+S+H+
  gene=LOC118511268 111 SAGGSVAAAVKLNKQ--ASEICINwGGGLHHAKKSEASGFCYVNDIVLGILELLK-Y-HQRVLYIDIDVHHGDGVEEAFYTTDRVMTVSFHK 198
                        *************99..999****9****************************99.4.58******************************** PP

                        -TTTSTTCCGSTT---SGGGTTSEEEEEESST-BHHHHHHHHHHTHHHHHHHH--SEEEEEEECTTBTTSTTTSBBB-HHHHHHHHHHHHHH CS
      Hist_deacetyl 184 yeesfyPgtgsleeigegkgkgktvnvplekgttdeeylkafeeillpaleefkPelivvsaGfDalkgDplgelnltaegyaeitkkllel 275
                        y ++++Pgtg+l++ig+g+gk ++vn+pl++g++de+y ++f  i+ +++e f+P+++v+++G+D+l gD+lg +nlt++g+ ++++++++
  gene=LOC118511268 199 Y-GEYFPGTGDLRDIGAGRGKYYAVNIPLRDGMDDESYDSIFVPIISKVMETFQPSAVVLQCGADSLTGDRLGCFNLTVKGHGKCVEFVKKY 289
                        9.559************************************************************************************999 PP

                        CGS..C-EEEEEECESSHHHHHHHHHHHHH CS
      Hist_deacetyl 276 aekvskrlvllleGGYnlealarsvtavla 305
                        +     +++++++GGY++++++r++t+ ++
  gene=LOC118511268 290 NL----PFLMVGGGGYTIRNVSRCWTYETS 315
                        98....89******************9986 PP

>> gene=LOC118517556  scaffold=NC_050202.1 strand=+ Parent=rna-XM_036063805.1
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc

# 2. Поиск квадруплексов и работа с Zhunt

Квадруплексы

In [44]:
%pip install pybedtools

import pybedtools
import pandas as pd
import re

Collecting pybedtools
  Downloading pybedtools-0.12.0.tar.gz (12.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 97.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pybedtools) (2.0.2)
Requirement already satisfied: pysam in /usr/local/lib/python3.12/dist-packages (from pybedtools) (0.24.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pybedtools) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pybedtools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pybedtools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pybedtools) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pybedtools) (1.17.0)
Building wheels for collected packages: pybedtools
  Building wheel for pybedtools (pyproject.toml) ... done
  Created wheel for pybedtools: filename=pybedtools-0.12.0-cp312-cp312-linux_x86_64.whl size=14340832 sha256=9e70dcbe98fd736f1961421c3949c3935c4fb1aa57e4ce186f4a2637afb84e03
  Stored in directory: /root/.cache/pip/wheels/ac/38/f2/960d79e44a92afc0d34a4727c856ce0149ac23c3dcda174356
Successfully built pybedtools
Installing collected packages: pybedtools
Successfully installed pybedtools-0.12.0

In [45]:
PQS = []
PQS_minus = []
pattern="(?:G{3,5}[ATGC]{1,7}){3,}G{3,5}"
pattern_minus="(?:C{3,5}[ATGC]{1,7}){3,}C{3,5}"
for scaffold, record in scaffolds.items():
    name, sequence = record.id, str(record.seq)
    PQS += [[name, m.start(),m.end(),m.group(0), name, '+'] for m in re.finditer(pattern,sequence,re.IGNORECASE)]
    PQS_minus += [[name, m.start(),m.end(),m.group(0), name, '-'] for m in re.finditer(pattern_minus,sequence,re.IGNORECASE)]
print(len(PQS))
print(len(PQS_minus))

8698
8620

In [46]:
quadrs = pd.DataFrame(PQS+PQS_minus, columns=['Chromosome', 'Start', 'End', 'Sequence', 'Name', 'Strand'])
quadrs

,Chromosome,Start,End,Sequence,Name,Strand
0,NC_050201.1,133214,133243,GGGGATTTTACGGGATGGGATGATGCGGG,NC_050201.1,+
1,NC_050201.1,134771,134795,ggggggggggagggggagggtggG,NC_050201.1,+
2,NC_050201.1,135062,135081,GGGTAGGGATCGGGTAGGG,NC_050201.1,+
3,NC_050201.1,234992,235010,GGGCTGGGCTGGGGCGGG,NC_050201.1,+
4,NC_050201.1,246043,246060,ggggggggggggggggg,NC_050201.1,+
...,...,...,...,...,...,...
17313,NW_023405470.1,10434,10456,cccagcagaccctcccagACCC,NW_023405470.1,-
17314,NW_023405470.1,33834,33857,cCCCTCCCCTCATCCCCCTGCCC,NW_023405470.1,-
17315,NW_023405470.1,38555,38595,CCCTGGGCCGCCCTGTTTTCCCCCGTGGTTCCCAGTGCCC,NW_023405470.1,-
17316,NW_023405470.1,41582,41609,CCCGAAGAGGCCCACCCAACCCacccc,NW_023405470.1,-
17317,NW_023405470.1,41856,41888,CCCCGGTCGTACCCTTTCCCCCTGTACACCCC,NW_023405470.1,-

In [47]:
from fuc import pybed
bf = pybed.BedFrame.from_frame(meta=[], data=quadrs)
bf.to_file('quadruplex.bed')

In [48]:
# Загрузка аннотации GFF
!gdown "19TECLovpngLrwcamfVbsX5kncOfs4htI" # genomic.gff

annotation_df = pd.read_csv(
    'genomic.gff',
    sep='\t',
    comment='#',
    header=None,
    names=["scaffold", "source", "type", "start", "end", "score", "strand", "phase", "attributes"]
)

annotation_df.head()

Downloading...
From (original): https://drive.google.com/uc?id=19TECLovpngLrwcamfVbsX5kncOfs4htI
From (redirected): https://drive.google.com/uc?id=19TECLovpngLrwcamfVbsX5kncOfs4htI&confirm=t&uuid=b6bdadb0-e038-4187-8392-e7016efb4064
To: /content/genomic.gff
100% 132M/132M [00:04<00:00, 31.1MB/s]

,scaffold,source,type,start,end,score,strand,phase,attributes
0,NC_050201.1,RefSeq,region,1,22713616,.,+,.,ID=NC_050201.1:1..22713616;Dbxref=taxon:30069;...
1,NC_050201.1,Gnomon,gene,5174,7880,.,-,.,ID=gene-LOC118517478;Dbxref=GeneID:118517478;N...
2,NC_050201.1,Gnomon,lnc_RNA,5174,7880,.,-,.,ID=rna-XR_004908317.1;Parent=gene-LOC118517478...
3,NC_050201.1,Gnomon,exon,7498,7880,.,-,.,ID=exon-XR_004908317.1-1;Parent=rna-XR_0049083...
4,NC_050201.1,Gnomon,exon,6206,7431,.,-,.,ID=exon-XR_004908317.1-2;Parent=rna-XR_0049083...

Разбиение аннотации

In [49]:
with open('scaffolds_sizes.txt', 'w') as out:
    for scaffold in scaffolds:
        scaffold_name = scaffold
        scaffold_length = len(scaffolds[scaffold].seq)
        out.write(f"{scaffold_name}\t{scaffold_length}\n")

In [50]:
def add_introns(annotation_df):
    introns = []
    for gene in annotation_df[annotation_df['type'] == 'gene'].itertuples():
        gene_exons = annotation_df[(annotation_df['type'] == 'exon') &
                                   (annotation_df['scaffold'] == gene.scaffold) &
                                   (annotation_df['start'] >= gene.start) &
                                   (annotation_df['end'] <= gene.end)]
        gene_exons = gene_exons.sort_values(by='start')
        previous_exon_end = None
        for exon in gene_exons.itertuples():
            if previous_exon_end is not None:
                intron_start = previous_exon_end + 1
                intron_end = exon.start - 1
                if intron_start < intron_end:
                    introns.append({
                        "scaffold": gene.scaffold,
                        "source": "predicted",
                        "type": "intron",
                        "start": intron_start,
                        "end": intron_end,
                        "score": ".",
                        "strand": gene.strand,
                        "phase": ".",
                        "attributes": gene.attributes
                    })
            previous_exon_end = exon.end

    introns_df = pd.DataFrame(introns)
    return pd.concat([annotation_df, introns_df], ignore_index=True)

annotation_intron_df = add_introns(annotation_df)

In [51]:
annotation_intron_df

,scaffold,source,type,start,end,score,strand,phase,attributes
0,NC_050201.1,RefSeq,region,1,22713616,.,+,.,ID=NC_050201.1:1..22713616;Dbxref=taxon:30069;...
1,NC_050201.1,Gnomon,gene,5174,7880,.,-,.,ID=gene-LOC118517478;Dbxref=GeneID:118517478;N...
2,NC_050201.1,Gnomon,lnc_RNA,5174,7880,.,-,.,ID=rna-XR_004908317.1;Parent=gene-LOC118517478...
3,NC_050201.1,Gnomon,exon,7498,7880,.,-,.,ID=exon-XR_004908317.1-1;Parent=rna-XR_0049083...
4,NC_050201.1,Gnomon,exon,6206,7431,.,-,.,ID=exon-XR_004908317.1-2;Parent=rna-XR_0049083...
...,...,...,...,...,...,...,...,...,...
533828,NW_023405470.1,predicted,intron,62781,62845,.,-,.,ID=gene-LOC118517349;Dbxref=GeneID:118517349;N...
533829,NW_023405470.1,predicted,intron,64151,64288,.,+,.,ID=gene-LOC118517350;Dbxref=GeneID:118517350;N...
533830,NW_023405470.1,predicted,intron,64419,64478,.,+,.,ID=gene-LOC118517350;Dbxref=GeneID:118517350;N...
533831,NW_023405470.1,predicted,intron,67065,67139,.,-,.,ID=gene-LOC118517348;Dbxref=GeneID:118517348;N...
533832,NW_023405470.1,predicted,intron,68222,68295,.,+,.,ID=gene-LOC118517355;Dbxref=GeneID:118517355;N...

In [52]:
annotation_intron_df[['scaffold', 'start', 'end', 'type', 'scaffold', 'strand']].to_csv('annotation.bed', header=None, index=False, sep='\t')

In [53]:
!awk '$4 == "exon"' annotation.bed > exons.bed
!awk '$4 == "intron"' annotation.bed > introns.bed
!awk '$4 == "gene"' annotation.bed > genes.bed

!bedtools complement -i genes.bed -g scaffolds_sizes.txt > intergenic.bed
!bedtools flank -i genes.bed -g scaffolds_sizes.txt -l 1000 -r 0 -s > promoters.bed
!bedtools flank -i genes.bed -g scaffolds_sizes.txt -l 0 -r 200 -s > downstream.bed

!bedtools intersect -a quadruplex.bed -b exons.bed -u > quadr_in_exons.bed
!bedtools intersect -a quadruplex.bed -b introns.bed -u > quadr_in_introns.bed
!bedtools intersect -a quadruplex.bed -b promoters.bed -u > quadr_in_promoters.bed
!bedtools intersect -a quadruplex.bed -b downstream.bed -u > quadr_in_downstream.bed
!bedtools intersect -a quadruplex.bed -b intergenic.bed -u > quadr_in_intergenic.bed

In [54]:
!wc -l quadr_in_exons.bed
!wc -l quadr_in_introns.bed
!wc -l quadr_in_promoters.bed
!wc -l quadr_in_downstream.bed
!wc -l quadr_in_intergenic.bed
!wc -l quadruplex.bed

2548 quadr_in_exons.bed
9193 quadr_in_introns.bed
740 quadr_in_promoters.bed
145 quadr_in_downstream.bed
5812 quadr_in_intergenic.bed
17318 quadruplex.bed

In [55]:
!bedtools intersect -a exons.bed -b quadruplex.bed -wa > exons_with_quadr.bed
!wc -l exons_with_quadr.bed
!wc -l exons.bed

8013 exons_with_quadr.bed
229796 exons.bed

In [56]:
%%bash
bedtools intersect -a introns.bed -b quadruplex.bed -wa > introns_with_quadr.bed
wc -l introns_with_quadr.bed
wc -l introns.bed

9603 introns_with_quadr.bed
62211 introns.bed

In [57]:
%%bash
bedtools intersect -a promoters.bed -b quadruplex.bed -wa > promoters_with_quadr.bed
wc -l promoters_with_quadr.bed
wc -l promoters.bed

769 promoters_with_quadr.bed
15186 promoters.bed

In [58]:
%%bash
bedtools intersect -a downstream.bed -b quadruplex.bed -wa > downstream_with_quadr.bed
wc -l downstream_with_quadr.bed
wc -l downstream.bed

151 downstream_with_quadr.bed
15187 downstream.bed

In [59]:
!bedtools intersect -a intergenic.bed -b quadruplex.bed -wa > intergenic_with_quadr.bed
!wc -l intergenic_with_quadr.bed
!wc -l intergenic.bed

5812 intergenic_with_quadr.bed
12343 intergenic.bed

Zhunt

In [60]:
!gcc zhunt.c -lm -o zhunt -D_THREAD_SAFE

cc1: fatal error: zhunt.c: No such file or directory
compilation terminated.

In [61]:
#!./zhunt 12 8 12 GCF_013141755.1_UCI_ANSTEP_V1.0_genomic.fna

In [62]:
!gdown "1N_-vMLwN0t6m4PjEdFgY7VySCiXwC1qE"

Downloading...
From (original): https://drive.google.com/uc?id=1N_-vMLwN0t6m4PjEdFgY7VySCiXwC1qE
From (redirected): https://drive.google.com/uc?id=1N_-vMLwN0t6m4PjEdFgY7VySCiXwC1qE&confirm=t&uuid=37eebbd2-241f-4a64-bd85-bd23f8860ebf
To: /content/GCF_013141755.1_UCI_ANSTEP_V1.0_genomic.fna.Z-SCORE
100% 277M/277M [00:05<00:00, 54.0MB/s]

In [63]:
df = pd.read_csv(
    'GCF_013141755.1_UCI_ANSTEP_V1.0_genomic.fna.Z-SCORE',
              skiprows=1,
              names=["start","end","3","4","5","score","seq","8"],
              delim_whitespace=True,
              chunksize=10000)

filtered_df = pd.concat(df, ignore_index=True)
filtered_df

/tmp/ipykernel_2658/953040244.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(

,start,end,3,4,5,score,seq,8
0,9331,9347,16,22.193,31.692,328.4535,gctacacgcgcaaagc,ASASASASASASSASA
1,9327,9343,16,22.202,30.342,325.3277,ctttgctacacgcgca,SASAASASASASASAS
2,9333,9349,16,22.195,31.585,327.5571,tacacgcgcaaagctg,ASASASASASASASAS
3,9329,9345,16,22.181,31.783,332.9764,ttgctacacgcgcaaa,SAASASASASASASAS
4,12099,12115,16,22.227,36.007,316.3602,ttgctgcacgcacaaa,SAASASASASASASAS
...,...,...,...,...,...,...,...,...
2953153,243470464,243470480,16,21.833,39.285,495.5430,tctcacgcacacacgg,SASASASASASASASA
2953154,243471088,243471112,24,20.752,34.724,1877.7650,ccggtggagactcgcgcacgcccg,ASASASASASASASASASASASAS
2953155,243471096,243471112,16,19.911,44.729,5864.6640,gactcgcgcacgcccg,ASASASASASASASAS
2953156,243473456,243473480,24,20.225,51.094,3794.7410,gggttacacacacgtgtgtgtggg,SASAASASASASASASASASASAS
2953157,243473464,243473482,18,20.132,59.259,4310.4600,cacacgtgtgtgtgggtg,ASASASASASASASASAS

In [64]:
zhunt_df = filtered_df[filtered_df['score'] > 400].reset_index(drop=True)
zhunt_df

,start,end,3,4,5,score,seq,8
0,30244,30260,16,21.625,41.959,632.7099,cgcgatgcgcctgcgc,ASSASASASASASASA
1,30248,30266,18,21.951,38.769,432.3963,atgcgcctgcgctgaagt,SASASASASASASASASA
2,30242,30260,18,21.943,38.944,436.3609,atcgcgatgcgcctgcgc,SAASSASASASASASASA
3,39388,39406,18,21.072,43.306,1245.8390,gaatttgtgcgcatgtgc,SASASASASASASASASA
4,39387,39409,22,21.046,47.065,1287.7860,tgaatttgtgcgcatgtgcctg,ASASASASASASASASASASAS
...,...,...,...,...,...,...,...,...
2455105,243470464,243470480,16,21.833,39.285,495.5430,tctcacgcacacacgg,SASASASASASASASA
2455106,243471088,243471112,24,20.752,34.724,1877.7650,ccggtggagactcgcgcacgcccg,ASASASASASASASASASASASAS
2455107,243471096,243471112,16,19.911,44.729,5864.6640,gactcgcgcacgcccg,ASASASASASASASAS
2455108,243473456,243473480,24,20.225,51.094,3794.7410,gggttacacacacgtgtgtgtggg,SASAASASASASASASASASASAS
2455109,243473464,243473482,18,20.132,59.259,4310.4600,cacacgtgtgtgtgggtg,ASASASASASASASASAS

In [65]:
zhunt_sorted = zhunt_df.sort_values(by=['start'])
zhunt_sorted[1] = 'genome'
zhunt_sorted[[1, 'start', 'end', 'score', 'seq']].to_csv('zscore_sorted.bed', sep='\t', header=None, index=False)

In [66]:
!bedtools merge -i zscore_sorted.bed > zscore_merged.bed

In [67]:
zhunt_coords = pd.read_csv('zscore_merged.bed', sep='\t', names=['place', 'start', 'end'])
zhunt_coords

         place      start        end
0       genome      30242      30266
1       genome      39382      39412
2       genome      46374      46392
3       genome      52912      52928
4       genome      57977      58005
...        ...        ...        ...
218792  genome  243469860  243469893
218793  genome  243470455  243470485
218794  genome  243471087  243471118
218795  genome  243473277  243473293
218796  genome  243473450  243473490

[218797 rows x 3 columns]

скаффолды

In [68]:
region_df = annotation_df[annotation_df['type'] == 'region'].reset_index(drop=True)
region_df

,scaffold,source,type,start,end,score,strand,phase,attributes
0,NC_050201.1,RefSeq,region,1,22713616,.,+,.,ID=NC_050201.1:1..22713616;Dbxref=taxon:30069;...
1,NC_050202.1,RefSeq,region,1,93706023,.,+,.,ID=NC_050202.1:1..93706023;Dbxref=taxon:30069;...
2,NC_050203.1,RefSeq,region,1,88747589,.,+,.,ID=NC_050203.1:1..88747589;Dbxref=taxon:30069;...
3,NW_023404980.1,RefSeq,region,1,61276,.,+,.,ID=NW_023404980.1:1..61276;Dbxref=taxon:30069;...
4,NW_023404981.1,RefSeq,region,1,43775,.,+,.,ID=NW_023404981.1:1..43775;Dbxref=taxon:30069;...
...,...,...,...,...,...,...,...,...,...
489,NW_023405466.1,RefSeq,region,1,58513,.,+,.,ID=NW_023405466.1:1..58513;Dbxref=taxon:30069;...
490,NW_023405467.1,RefSeq,region,1,48590,.,+,.,ID=NW_023405467.1:1..48590;Dbxref=taxon:30069;...
491,NW_023405468.1,RefSeq,region,1,107798,.,+,.,ID=NW_023405468.1:1..107798;Dbxref=taxon:30069...
492,NW_023405469.1,RefSeq,region,1,61267,.,+,.,ID=NW_023405469.1:1..61267;Dbxref=taxon:30069;...
493,NW_023405470.1,RefSeq,region,1,74515,.,+,.,ID=NW_023405470.1:1..74515;Dbxref=taxon:30069;...

In [69]:
region_df['global_end'] = region_df['end'].cumsum()
region_df.head()

,scaffold,source,type,start,end,score,strand,phase,attributes,global_end
0,NC_050201.1,RefSeq,region,1,22713616,.,+,.,ID=NC_050201.1:1..22713616;Dbxref=taxon:30069;...,22713616
1,NC_050202.1,RefSeq,region,1,93706023,.,+,.,ID=NC_050202.1:1..93706023;Dbxref=taxon:30069;...,116419639
2,NC_050203.1,RefSeq,region,1,88747589,.,+,.,ID=NC_050203.1:1..88747589;Dbxref=taxon:30069;...,205167228
3,NW_023404980.1,RefSeq,region,1,61276,.,+,.,ID=NW_023404980.1:1..61276;Dbxref=taxon:30069;...,205228504
4,NW_023404981.1,RefSeq,region,1,43775,.,+,.,ID=NW_023404981.1:1..43775;Dbxref=taxon:30069;...,205272279

In [70]:
i_scaffold = 0
scaffold_start = 0
scaffold_end = 22713616
scaffold = 'NC_050201.1'

corrected_records = []

for index, row in zhunt_coords.iterrows():
    zdna_start = row['start']
    zdna_end = row['end']
    if zdna_start > scaffold_end:
        i_scaffold += 1
        if i_scaffold >= len(region_df):
            break

    if i_scaffold > 0:
        prev_cumulative_end = region_df.iloc[i_scaffold - 1]['global_end']
        scaffold_end = region_df.iloc[i_scaffold]['global_end']
        scaffold = region_df.iloc[i_scaffold]['scaffold']
    else:
        prev_cumulative_end = 0

    corrected_start = zdna_start - prev_cumulative_end
    corrected_end = zdna_end - prev_cumulative_end
    corrected_records.append({
            'scaffold': scaffold,
            'start': corrected_start,
            'end': corrected_end,
        })

corrected_zhunt_df = pd.DataFrame(corrected_records)
corrected_zhunt_df.head()

      scaffold  start    end
0  NC_050201.1  30242  30266
1  NC_050201.1  39382  39412
2  NC_050201.1  46374  46392
3  NC_050201.1  52912  52928
4  NC_050201.1  57977  58005

In [71]:
corrected_zhunt_df[[4, 5, 6]] = [4, 5, 6]
corrected_zhunt_df

              scaffold  start    end  4  5  6
0          NC_050201.1  30242  30266  4  5  6
1          NC_050201.1  39382  39412  4  5  6
2          NC_050201.1  46374  46392  4  5  6
3          NC_050201.1  52912  52928  4  5  6
4          NC_050201.1  57977  58005  4  5  6
...                ...    ...    ... .. .. ..
218771  NW_023405470.1  72079  72100  4  5  6
218772  NW_023405470.1  72289  72305  4  5  6
218773  NW_023405470.1  72392  72427  4  5  6
218774  NW_023405470.1  74055  74086  4  5  6
218775  NW_023405470.1  74442  74468  4  5  6

[218776 rows x 6 columns]

In [72]:
corrected_zhunt_df.to_csv('zhunt.bed', sep='\t', header=None, index=False)

Результаты

In [73]:
!bedtools intersect -a zhunt.bed -b exons.bed -u > zhunt_in_exons.bed
!cat zhunt_in_exons.bed | wc -l

53675

In [74]:
!bedtools intersect -a zhunt.bed -b introns.bed -u > zhunt_in_introns.bed
!cat zhunt_in_introns.bed | wc -l

101047

In [75]:
!bedtools intersect -a zhunt.bed -b promoters.bed -u > zhunt_in_promoters.bed
!cat zhunt_in_promoters.bed | wc -l

13208

In [76]:
!bedtools intersect -a zhunt.bed -b downstream.bed -u > zhunt_in_downstream.bed
!cat zhunt_in_downstream.bed | wc -l

!bedtools intersect -a zhunt.bed -b intergenic.bed -u > zhunt_in_intergenic.bed
!cat zhunt_in_intergenic.bed | wc -l

!cat zhunt.bed | wc -l

2367
69180
218776

-------

In [77]:
!bedtools intersect -a exons.bed -b zhunt.bed -wa > exons_with_zhunt_all.bed
!sort -u exons_with_zhunt_all.bed > exons_with_zhunt.bed
!cat exons_with_zhunt.bed | wc -l
!cat exons.bed | wc -l

31691
229796

In [78]:
!bedtools intersect -a introns.bed -b zhunt.bed -wa > introns_with_zhunt_all.bed
!sort -u introns_with_zhunt_all.bed > introns_with_zhunt.bed
!cat introns_with_zhunt.bed | wc -l
!cat introns.bed | wc -l

18581
62211

In [79]:
!bedtools intersect -a promoters.bed -b zhunt.bed -wa > promoters_with_zhunt_all.bed
!sort -u promoters_with_zhunt_all.bed > promoters_with_zhunt.bed
!cat promoters_with_zhunt.bed | wc -l
!cat promoters.bed | wc -l

8262
15186

In [80]:
!bedtools intersect -a downstream.bed -b zhunt.bed -wa > downstream_with_zhunt_all.bed
!sort -u downstream_with_zhunt_all.bed > downstream_with_zhunt.bed
!cat downstream_with_zhunt.bed | wc -l
!cat downstream.bed | wc -l

2191
15187

In [81]:
!bedtools intersect -a intergenic.bed -b zhunt.bed -wa > intergenic_with_zhunt_all.bed
!sort -u intergenic_with_zhunt_all.bed > intergenic_with_zhunt.bed
!cat intergenic_with_zhunt.bed | wc -l
!cat intergenic.bed | wc -l

6584
12343

# 3. ZDNABERT

In [82]:
from Bio import SeqIO

# Название нужной хромосомы/скаффолда
target = "NC_050201.1"

# Если scaffolds уже существует
SeqIO.write(scaffolds[target], "NC_050201.1.fasta", "fasta")

1

In [83]:
rec = next(SeqIO.parse("NC_050201.1.fasta", "fasta"))
print(rec.id)
print(len(rec.seq))

NC_050201.1
22713616

In [84]:
!grep "^NC_050201.1" exons.bed > exons_chr.bed
!grep "^NC_050201.1" introns.bed > introns_chr.bed
!grep "^NC_050201.1" genes.bed > genes_chr.bed
!grep "^NC_050201.1" promoters.bed > promoters_chr.bed
!grep "^NC_050201.1" downstream.bed > downstream_chr.bed
!grep "^NC_050201.1" intergenic.bed > intergenic_chr.bed

In [85]:
!bedtools intersect -a zdnabert.bed -b exons_chr.bed -u > zdna_in_exons.bed
!bedtools intersect -a zdnabert.bed -b introns_chr.bed -u > zdna_in_introns.bed
!bedtools intersect -a zdnabert.bed -b promoters_chr.bed -u > zdna_in_promoters.bed
!bedtools intersect -a zdnabert.bed -b downstream_chr.bed -u > zdna_in_downstream.bed
!bedtools intersect -a zdnabert.bed -b intergenic_chr.bed -u > zdna_in_intergenic.bed

In [86]:
!wc -l zdna_in_exons.bed
!wc -l zdna_in_introns.bed
!wc -l zdna_in_promoters.bed
!wc -l zdna_in_downstream.bed
!wc -l zdna_in_intergenic.bed
!wc -l zdnabert.bed

3992 zdna_in_exons.bed
5027 zdna_in_introns.bed
826 zdna_in_promoters.bed
85 zdna_in_downstream.bed
3415 zdna_in_intergenic.bed
12266 zdnabert.bed

In [87]:
!bedtools intersect -a exons_chr.bed -b zdnabert.bed -wa > exons_with_zdna_all.bed
!sort -u exons_with_zdna_all.bed > exons_with_zdna.bed

!bedtools intersect -a introns_chr.bed -b zdnabert.bed -wa > introns_with_zdna_all.bed
!sort -u introns_with_zdna_all.bed > introns_with_zdna.bed

!bedtools intersect -a promoters_chr.bed -b zdnabert.bed -wa > promoters_with_zdna_all.bed
!sort -u promoters_with_zdna_all.bed > promoters_with_zdna.bed

!bedtools intersect -a downstream_chr.bed -b zdnabert.bed -wa > downstream_with_zdna_all.bed
!sort -u downstream_with_zdna_all.bed > downstream_with_zdna.bed

!bedtools intersect -a intergenic_chr.bed -b zdnabert.bed -wa > intergenic_with_zdna_all.bed
!sort -u intergenic_with_zdna_all.bed > intergenic_with_zdna.bed

In [88]:
!wc -l exons_with_zdna.bed
!wc -l exons_chr.bed

!wc -l introns_with_zdna.bed
!wc -l introns_chr.bed

!wc -l promoters_with_zdna.bed
!wc -l promoters_chr.bed

!wc -l downstream_with_zdna.bed
!wc -l downstream_chr.bed

!wc -l intergenic_with_zdna.bed
!wc -l intergenic_chr.bed

2568 exons_with_zdna.bed
24337 exons_chr.bed
1296 introns_with_zdna.bed
6625 introns_chr.bed
515 promoters_with_zdna.bed
1401 promoters_chr.bed
75 downstream_with_zdna.bed
1401 downstream_chr.bed
447 intergenic_with_zdna.bed
1092 intergenic_chr.bed

In [89]:
def wc(fname):
    with open(fname) as f:
        return sum(1 for _ in f)

total = wc("zdnabert.bed")

print("Exons:", wc("zdna_in_exons.bed") / total)
print("Introns:", wc("zdna_in_introns.bed") / total)
print("Promoters:", wc("zdna_in_promoters.bed") / total)
print("Downstream:", wc("zdna_in_downstream.bed") / total)
print("Intergenic:", wc("zdna_in_intergenic.bed") / total)

Exons: 0.325452470242948
Introns: 0.4098320560900049
Promoters: 0.06734061633784445
Downstream: 0.0069297244415457366
Intergenic: 0.27841187021033753

Квадруплексы и zhunt для одной хромосомы (для сравнения):

In [90]:
!grep "^NC_050201.1" quadruplex.bed > quadruplex_chr.bed
!grep "^NC_050201.1" zhunt.bed > zhunt_chr.bed

In [91]:
!wc -l quadruplex_chr.bed
!wc -l zhunt_chr.bed

2817 quadruplex_chr.bed
21874 zhunt_chr.bed

In [92]:
!bedtools intersect -a quadruplex_chr.bed -b exons_chr.bed -u > quadr_in_exons_chr.bed
!bedtools intersect -a quadruplex_chr.bed -b introns_chr.bed -u > quadr_in_introns_chr.bed
!bedtools intersect -a quadruplex_chr.bed -b promoters_chr.bed -u > quadr_in_promoters_chr.bed
!bedtools intersect -a quadruplex_chr.bed -b downstream_chr.bed -u > quadr_in_downstream_chr.bed
!bedtools intersect -a quadruplex_chr.bed -b intergenic_chr.bed -u > quadr_in_intergenic_chr.bed

In [93]:
!wc -l quadr_in_exons_chr.bed
!wc -l quadr_in_introns_chr.bed
!wc -l quadr_in_promoters_chr.bed
!wc -l quadr_in_downstream_chr.bed
!wc -l quadr_in_intergenic_chr.bed
!wc -l quadruplex_chr.bed

436 quadr_in_exons_chr.bed
1406 quadr_in_introns_chr.bed
148 quadr_in_promoters_chr.bed
30 quadr_in_downstream_chr.bed
1011 quadr_in_intergenic_chr.bed
2817 quadruplex_chr.bed

In [94]:
!bedtools intersect -a zhunt_chr.bed -b exons_chr.bed -u > zhunt_in_exons_chr.bed
!bedtools intersect -a zhunt_chr.bed -b introns_chr.bed -u > zhunt_in_introns_chr.bed
!bedtools intersect -a zhunt_chr.bed -b promoters_chr.bed -u > zhunt_in_promoters_chr.bed
!bedtools intersect -a zhunt_chr.bed -b downstream_chr.bed -u > zhunt_in_downstream_chr.bed
!bedtools intersect -a zhunt_chr.bed -b intergenic_chr.bed -u > zhunt_in_intergenic_chr.bed

In [95]:
!wc -l zhunt_in_exons_chr.bed
!wc -l zhunt_in_introns_chr.bed
!wc -l zhunt_in_promoters_chr.bed
!wc -l zhunt_in_downstream_chr.bed
!wc -l zhunt_in_intergenic_chr.bed
!wc -l zhunt_chr.bed

6639 zhunt_in_exons_chr.bed
9391 zhunt_in_introns_chr.bed
1422 zhunt_in_promoters_chr.bed
212 zhunt_in_downstream_chr.bed
6415 zhunt_in_intergenic_chr.bed
21874 zhunt_chr.bed

In [96]:
!bedtools intersect -a exons_chr.bed -b quadruplex_chr.bed -wa > exons_with_quadr_all.bed
!sort -u exons_with_quadr_all.bed > exons_with_quadr_chr.bed

!bedtools intersect -a introns_chr.bed -b quadruplex_chr.bed -wa > introns_with_quadr_all.bed
!sort -u introns_with_quadr_all.bed > introns_with_quadr_chr.bed

!bedtools intersect -a promoters_chr.bed -b quadruplex_chr.bed -wa > promoters_with_quadr_all.bed
!sort -u promoters_with_quadr_all.bed > promoters_with_quadr_chr.bed

!bedtools intersect -a downstream_chr.bed -b quadruplex_chr.bed -wa > downstream_with_quadr_all.bed
!sort -u downstream_with_quadr_all.bed > downstream_with_quadr_chr.bed

!bedtools intersect -a intergenic_chr.bed -b quadruplex_chr.bed -wa > intergenic_with_quadr_all.bed
!sort -u intergenic_with_quadr_all.bed > intergenic_with_quadr_chr.bed

In [97]:
!bedtools intersect -a exons_chr.bed -b zhunt_chr.bed -wa > exons_with_zhunt_all.bed
!sort -u exons_with_zhunt_all.bed > exons_with_zhunt_chr.bed

!bedtools intersect -a introns_chr.bed -b zhunt_chr.bed -wa > introns_with_zhunt_all.bed
!sort -u introns_with_zhunt_all.bed > introns_with_zhunt_chr.bed

!bedtools intersect -a promoters_chr.bed -b zhunt_chr.bed -wa > promoters_with_zhunt_all.bed
!sort -u promoters_with_zhunt_all.bed > promoters_with_zhunt_chr.bed

!bedtools intersect -a downstream_chr.bed -b zhunt_chr.bed -wa > downstream_with_zhunt_all.bed
!sort -u downstream_with_zhunt_all.bed > downstream_with_zhunt_chr.bed

!bedtools intersect -a intergenic_chr.bed -b zhunt_chr.bed -wa > intergenic_with_zhunt_all.bed
!sort -u intergenic_with_zhunt_all.bed > intergenic_with_zhunt_chr.bed

In [98]:
%%bash

echo "========== TOTAL =========="

echo "Quadruplex:"
wc -l quadruplex_chr.bed

echo "Zhunt:"
wc -l zhunt_chr.bed

echo "ZDNABERT:"
wc -l zdnabert.bed


echo
echo "========== TABLE 1 (number of predictions) =========="

echo "Quadruplex"
wc -l quadr_in_exons_chr.bed
wc -l quadr_in_introns_chr.bed
wc -l quadr_in_promoters_chr.bed
wc -l quadr_in_downstream_chr.bed
wc -l quadr_in_intergenic_chr.bed

echo
echo "Zhunt"
wc -l zhunt_in_exons_chr.bed
wc -l zhunt_in_introns_chr.bed
wc -l zhunt_in_promoters_chr.bed
wc -l zhunt_in_downstream_chr.bed
wc -l zhunt_in_intergenic_chr.bed

echo
echo "ZDNABERT"
wc -l zdna_in_exons.bed
wc -l zdna_in_introns.bed
wc -l zdna_in_promoters.bed
wc -l zdna_in_downstream.bed
wc -l zdna_in_intergenic.bed


echo
echo "========== TABLE 2 (regions with predictions) =========="

echo "TOTAL REGIONS"
wc -l exons_chr.bed
wc -l introns_chr.bed
wc -l promoters_chr.bed
wc -l downstream_chr.bed
wc -l intergenic_chr.bed

echo
echo "Quadruplex"
wc -l exons_with_quadr_chr.bed
wc -l introns_with_quadr_chr.bed
wc -l promoters_with_quadr_chr.bed
wc -l downstream_with_quadr_chr.bed
wc -l intergenic_with_quadr_chr.bed

echo
echo "Zhunt"
wc -l exons_with_zhunt_chr.bed
wc -l introns_with_zhunt_chr.bed
wc -l promoters_with_zhunt_chr.bed
wc -l downstream_with_zhunt_chr.bed
wc -l intergenic_with_zhunt_chr.bed

echo
echo "ZDNABERT"
wc -l exons_with_zdna.bed
wc -l introns_with_zdna.bed
wc -l promoters_with_zdna.bed
wc -l downstream_with_zdna.bed
wc -l intergenic_with_zdna.bed

========== TOTAL ==========
Quadruplex:
2817 quadruplex_chr.bed
Zhunt:
21874 zhunt_chr.bed
ZDNABERT:
12266 zdnabert.bed

========== TABLE 1 (number of predictions) ==========
Quadruplex
436 quadr_in_exons_chr.bed
1406 quadr_in_introns_chr.bed
148 quadr_in_promoters_chr.bed
30 quadr_in_downstream_chr.bed
1011 quadr_in_intergenic_chr.bed

Zhunt
6639 zhunt_in_exons_chr.bed
9391 zhunt_in_introns_chr.bed
1422 zhunt_in_promoters_chr.bed
212 zhunt_in_downstream_chr.bed
6415 zhunt_in_intergenic_chr.bed

ZDNABERT
3992 zdna_in_exons.bed
5027 zdna_in_introns.bed
826 zdna_in_promoters.bed
85 zdna_in_downstream.bed
3415 zdna_in_intergenic.bed

========== TABLE 2 (regions with predictions) ==========
TOTAL REGIONS
24337 exons_chr.bed
6625 introns_chr.bed
1401 promoters_chr.bed
1401 downstream_chr.bed
1092 intergenic_chr.bed

Quadruplex
385 exons_with_quadr_chr.bed
696 introns_with_quadr_chr.bed
136 promoters_with_quadr_chr.bed
29 downstream_with_quadr_chr.bed
292 intergenic_with_quadr_chr.bed

Zhunt
3754 exons_with_zhunt_chr.bed
2049 introns_with_zhunt_chr.bed
820 promoters_with_zhunt_chr.bed
198 downstream_with_zhunt_chr.bed
673 intergenic_with_zhunt_chr.bed

ZDNABERT
2568 exons_with_zdna.bed
1296 introns_with_zdna.bed
515 promoters_with_zdna.bed
75 downstream_with_zdna.bed
447 intergenic_with_zdna.bed

Фон

In [99]:
%%bash

echo "Exons"
awk '{sum += $3-$2} END {print sum}' exons.bed

echo "Introns"
awk '{sum += $3-$2} END {print sum}' introns.bed

echo "Promoters"
awk '{sum += $3-$2} END {print sum}' promoters.bed

echo "Downstream"
awk '{sum += $3-$2} END {print sum}' downstream.bed

echo "Intergenic"
awk '{sum += $3-$2} END {print sum}' intergenic.bed

Exons
142161798
Introns
111815113
Promoters
15161569
Downstream
3035982
Intergenic
92022024